/**
 * 大师经验库 — 扩展经验 (0023-0050)
 *
 * 覆盖：供应链、营销、融资、危机管理、数字化转型、团队管理、竞争策略
 */
import type { MasterExperience } from "../types";

export const EXTENDED_EXPERIENCES: MasterExperience[] = [
  {
    id: "MK-MASTER-0023",
    topic: "供应链",
    question: "供应链管理的核心是什么？",
    wisdom: "供应链不是找最便宜的，是找最稳定的。",
    scenario: "供应链管理",
    reasoning: "餐饮品质的一致性依赖供应链的稳定性。便宜但不稳定的供应商，会导致品质波动和断货风险。",
    risks: ["品质波动", "断货风险", "成本不可控"],
    application: "选择2-3家稳定供应商，建立长期合作关系",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0024",
    topic: "营销",
    question: "餐饮营销的核心是什么？",
    wisdom: "最好的营销是让顾客帮你传播。口碑>广告>促销。",
    scenario: "营销策略",
    reasoning: "餐饮是体验型消费，口碑是最有效的获客方式。广告和促销只能带来首次消费，口碑才能带来复购。",
    risks: ["营销成本高", "效果不可持续", "依赖流量"],
    application: "把营销预算投入产品和体验，让顾客自发传播",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0025",
    topic: "融资",
    question: "什么时候应该融资？",
    wisdom: "融资的最佳时机是你不需要钱的时候。",
    scenario: "融资决策",
    reasoning: "当你不缺钱时融资，你有谈判筹码。当你急需钱时融资，你会被资本压榨。最好在单店模型验证成功后、扩张前融资。",
    risks: ["估值被压低", "失去控制权", "对赌风险"],
    application: "先验证单店盈利模型，再考虑融资扩张",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0026",
    topic: "加盟",
    question: "加盟还是直营？",
    wisdom: "没有标准化之前不要开放加盟，那是在收割信任。",
    scenario: "扩张策略",
    reasoning: "加盟不是品牌方的提款机。没有标准化体系就开放加盟，最终品牌会被加盟商拖垮。",
    risks: ["品牌受损", "加盟商维权", "管理失控"],
    application: "直营验证模型→建立标准化→开放加盟→持续赋能",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0027",
    topic: "人才",
    question: "餐饮怎么留住人才？",
    wisdom: "优秀的人才不是找来的，是培养出来的。",
    scenario: "人才管理",
    reasoning: "餐饮行业普遍缺人，但优秀的人才更看重成长空间。与其挖角不如自己培养，建立培训体系和晋升通道。",
    risks: ["人员流失", "培养成本", "管理断层"],
    application: "建立师徒制、晋升通道、股权激励机制",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0028",
    topic: "数字化",
    question: "小餐馆需要数字化吗？",
    wisdom: "先有好的运营，数字化才能放大价值。",
    scenario: "数字化转型",
    reasoning: "数字化是工具不是目的。如果你的产品、服务、流程本身有问题，数字化只会让问题暴露得更快。",
    risks: ["投入产出比低", "系统复杂", "忽视基础"],
    application: "先把产品和运营做好，再用数字化提升效率",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0029",
    topic: "危机",
    question: "遇到危机时最应该做什么？",
    wisdom: "危机时最重要的不是省钱，是保持核心团队。",
    scenario: "危机管理",
    reasoning: "危机终会过去，但核心团队一旦流失，恢复期会更长。保留核心团队，才能在危机后快速恢复。",
    risks: ["核心人员流失", "恢复期延长", "竞争力下降"],
    application: "危机时削减非核心开支，保留核心团队",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0030",
    topic: "菜单",
    question: "菜单应该怎么设计？",
    wisdom: "菜单不是菜品列表，是利润地图。",
    scenario: "菜单设计",
    reasoning: "菜单应该引导顾客选择高毛利菜品。招牌菜放在左上角，高毛利菜品用图片和特殊标识突出。菜单页数越少越好。",
    risks: ["顾客选择困难", "低毛利菜品占比高", "厨房效率低"],
    application: "设计菜单时先算毛利，把高利润菜品放在最显眼位置",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0031",
    topic: "竞争",
    question: "怎么应对周边新开的竞品？",
    wisdom: "不要盯着竞争对手，要盯着顾客。",
    scenario: "竞争策略",
    reasoning: "当你把精力放在研究竞争对手时，你已经输了。真正要做的是理解你的顾客为什么选择你，然后把这一点做到极致。",
    risks: ["陷入价格战", "失去自身特色", "资源分散"],
    application: "聚焦核心客群的需求，把差异化做到极致",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0032",
    topic: "选址",
    question: "社区店和商圈店怎么选？",
    wisdom: "社区店靠复购，商圈店靠流量。没有复购能力不要做社区店，没有品牌力不要进商圈。",
    scenario: "选址决策",
    reasoning: "社区店的核心是周边居民的复购率，需要品质稳定、性价比高。商圈店的核心是流量转化，需要品牌吸引力和差异化。",
    risks: ["选错位置类型", "客群不匹配", "成本结构失衡"],
    application: "新品牌先做社区店积累口碑，有品牌力后再进商圈",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0033",
    topic: "合伙",
    question: "合伙创业要注意什么？",
    wisdom: "合伙最怕的不是亏钱，是赚钱后怎么分。",
    scenario: "合伙创业",
    reasoning: "很多合伙创业死在赚钱之后。亏钱时大家齐心协力，赚钱时开始计较谁贡献大。必须在赚钱之前就把分配机制定清楚。",
    risks: ["利益分配纠纷", "决策权争夺", "散伙风险"],
    application: "开业前签订详细的合伙协议，包括：股权、分工、退出机制、决策权",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0034",
    topic: "扩张",
    question: "开第二家店的最佳时机？",
    wisdom: "当第一家店不需要你也能运转的时候。",
    scenario: "扩张决策",
    reasoning: "如果你离开第一家店一个月，业绩没有明显下降，说明你已经建立了可复制的系统。这才是开第二家店的时机。",
    risks: ["管理跟不上", "品质下降", "精力分散"],
    application: "先培养店长和建立SOP，确保第一家店能自主运转",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0035",
    topic: "定价",
    question: "怎么制定合理的价格？",
    wisdom: "定价不是成本加利润，是价值感知。",
    scenario: "定价策略",
    reasoning: "顾客不关心你的成本，只关心他获得的价值。定价要基于目标客群的支付意愿和竞争对手的价格带。",
    risks: ["定价过高无人问津", "定价过低利润不足", "价值感不匹配"],
    application: "研究目标客群的支付意愿，参考竞品定价，找到价值感最优的价格点",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0036",
    topic: "厨师",
    question: "如何降低对厨师的依赖？",
    wisdom: "好的餐厅不依赖厨师，依赖系统。",
    scenario: "后厨管理",
    reasoning: "厨师离职导致菜品品质波动是餐饮老板最大的噩梦。解决方法是：标准化所有菜品配方、操作流程、验收标准，让普通人也能做出好菜。",
    risks: ["核心厨师离职", "品质不稳定", "扩张受限"],
    application: "建立菜品标准卡（配方+操作步骤+照片），定期培训考核",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0037",
    topic: "顾客",
    question: "怎么处理顾客投诉？",
    wisdom: "投诉是礼物，不是麻烦。",
    scenario: "客诉处理",
    reasoning: "愿意投诉的顾客是想给你机会改进。不投诉直接不来的顾客才是最大的损失。每一个投诉都是一个改进机会。",
    risks: ["差评扩散", "顾客流失", "问题被忽视"],
    application: "建立投诉处理SOP：及时响应→真诚道歉→快速解决→跟进回访",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0038",
    topic: "创新",
    question: "餐饮创新应该怎么做？",
    wisdom: "创新要围绕顾客需求，不是老板的自嗨。",
    scenario: "产品创新",
    reasoning: "很多老板的创新是他自己的想法，不是顾客的需求。创新前要先调研、小范围测试、根据反馈迭代。",
    risks: ["脱离市场", "资源浪费", "顾客不买账"],
    application: "创新前先访谈顾客，测试最小可行产品，根据反馈快速迭代",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0039",
    topic: "效率",
    question: "怎么提升厨房效率？",
    wisdom: "厨房效率不是靠厨师跑得快，是靠流程设计得好。",
    scenario: "厨房管理",
    reasoning: "动线设计、设备布局、备料流程对效率的影响远大于厨师的速度。合理的设计可以让产能提升30%以上。",
    risks: ["出餐慢", "高峰期积压", "人力浪费"],
    application: "优化厨房动线，提前备料，设置出餐缓冲区",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0040",
    topic: "成本",
    question: "成本控制的核心是什么？",
    wisdom: "成本控制不是降低标准，是消除浪费。",
    scenario: "成本管理",
    reasoning: "很多老板为了控制成本降低食材品质，这是自杀。真正的成本控制是：减少损耗、提高效率、优化采购、降低库存。",
    risks: ["品质下降", "顾客流失", "品牌受损"],
    application: "用数据跟踪每一项成本的变动，找到浪费源头而非直接削减",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0041",
    topic: "淡季",
    question: "淡季怎么生存？",
    wisdom: "淡季不是等死，是练内功的最佳时机。",
    scenario: "淡季管理",
    reasoning: "很多餐厅淡季就躺平，等旺季再来。聪明的老板在淡季做：培训员工、优化流程、研发新品、维护设备、拓展新渠道。",
    risks: ["淡季亏损", "员工流失", "设备老化"],
    application: "制定淡季工作计划，把淡季变成升级期",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0042",
    topic: "外卖",
    question: "外卖怎么做才能赚钱？",
    wisdom: "外卖的本质不是把堂食的东西打包，而是重新设计一个适合配送的产品。",
    scenario: "外卖策略",
    reasoning: "堂食好吃的菜不一定适合外卖。外卖需要考虑：配送过程中的口感变化、包装成本、出餐效率。要专门设计外卖菜单。",
    risks: ["品质下降", "差评增多", "利润薄"],
    application: "设计专门的外卖菜单，选择适合配送的菜品，优化包装",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0043",
    topic: "品牌",
    question: "新品牌怎么建立认知？",
    wisdom: "新品牌不需要让所有人知道，只需要让目标客群记住一个词。",
    scenario: "品牌建设",
    reasoning: "新品牌最容易犯的错误是想表达太多东西。成功的品牌只让顾客记住一个词：海底捞=服务、巴奴=毛肚、西贝=西北菜。",
    risks: ["品牌定位模糊", "传播成本高", "认知混乱"],
    application: "找到你最核心的一个价值点，所有传播都围绕这一个点",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0044",
    topic: "数据",
    question: "餐饮老板应该关注哪些数据？",
    wisdom: "关注滞后指标（营收、利润），更要关注领先指标（客流、复购、好评率）。",
    scenario: "数据管理",
    reasoning: "营收和利润是结果指标，等你看到的时候已经来不及调整了。客流、复购率、好评率是先行指标，提前发现趋势才能及时调整。",
    risks: ["反应滞后", "问题积累", "错过调整时机"],
    application: "每天关注客流和好评率，每周关注复购率和成本率",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0045",
    topic: "合伙人",
    question: "怎么选择合伙人？",
    wisdom: "选合伙人不是选有钱的，是选能补你短板的。",
    scenario: "合伙创业",
    reasoning: "餐饮创业需要的核心能力：产品、运营、营销、管理、财务。一个人不可能全部具备，合伙人要能力互补而非重叠。",
    risks: ["能力重叠", "分工不清", "决策冲突"],
    application: "列出你最强的3个能力和最弱的3个能力，找能补短板的人合伙",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0046",
    topic: "节奏",
    question: "餐饮创业的节奏怎么把握？",
    wisdom: "餐饮是马拉松不是百米冲刺，急不得。",
    scenario: "创业节奏",
    reasoning: "餐饮需要时间积累口碑、磨合团队、优化产品。急于求成往往导致决策失误。很多倒闭的餐厅不是死在慢，是死在快。",
    risks: ["急于扩张", "忽视品质", "决策冲动"],
    application: "设定合理的时间预期：前6个月验证模型，第7-12个月优化，第二年再考虑扩张",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0047",
    topic: "心态",
    question: "餐饮创业最难的是什么？",
    wisdom: "最难的不是没钱没人没资源，是坚持对的判断。",
    scenario: "创业心态",
    reasoning: "餐饮创业过程中会有无数人给你建议：降价、促销、换位置、改菜单。最难的是在噪音中坚持你自己的判断，同时保持开放学习的心态。",
    risks: ["被外界干扰", "频繁试错", "失去方向"],
    application: "建立自己的经营哲学，用数据验证判断，而不是被情绪左右",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0048",
    topic: "竞争",
    question: "价格战怎么应对？",
    wisdom: "不要打价格战，要打价值战。",
    scenario: "竞争策略",
    reasoning: "价格战没有赢家。降价会压缩利润，降低品质，最终损害品牌。真正应该做的是提升价值感，让顾客觉得值得多付一点。",
    risks: ["利润下降", "品质下降", "恶性循环"],
    application: "找到你的差异化价值，让价格成为价值的反映而非竞争工具",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0049",
    topic: "二代",
    question: "餐饮二代接班要注意什么？",
    wisdom: "不要试图改变父辈的作风，用业绩说话。",
    scenario: "二代接班",
    reasoning: "餐饮二代接班最大的问题不是能力不足，是沟通方式不对。不要一开始就想推翻父辈的做法，先用数据证明你的方法有效。",
    risks: ["代际冲突", "改革失败", "团队分裂"],
    application: "从小处入手，用数据验证，用业绩赢得信任",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0050",
    topic: "长期",
    question: "做餐饮的终极目标是什么？",
    wisdom: "活下来比什么都重要。先活过3年，再谈品牌和梦想。",
    scenario: "长期经营",
    reasoning: "餐饮行业第一年倒闭率超过30%，3年超过50%。不要一开始就想做品牌、做连锁。先让自己活下来，活好了，自然会有品牌。",
    risks: ["目标过高", "投入过大", "无法坚持"],
    application: "把第一年的目标设为：活下来。第二年的目标：活好。第三年再考虑做大。",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
];
