/**
 * 特劳特定位理论 — 知识规则库
 * 
 * 蒸馏来源：定位、商战、与众不同、大品牌大问题、简单的力量、终结营销混乱
 */
import type { TheoryRule } from "./knowledge-loader";

export const troutRules: TheoryRule[] = [
  {
    id: "trout-competitive-positioning",
    theory_source: "trout",
    name: "竞争性定位",
    principle: "定位不是关于品牌的自我表达，而是关于品牌在竞争结构中的位置",
    decision_question: "在竞争地图中，你的位置在哪里？",
    applicable_context: ["任何品类竞争场景"],
    key_variables: ["竞品心智地图", "空位识别", "差异化方向"],
    decision_rules: [
      "在谈定位之前，先画出竞争地图——谁占据了哪个心智位置？",
      "你的位置是由竞争对手的位置决定的，不是由你自己的愿望决定的",
      "如果你说不清竞争对手是谁、占据了什么位置，你的定位就是凭感觉的",
    ],
    anti_patterns: [
      "不分析竞品就谈定位",
      "只分析直接竞品而忽略替代性竞争",
      "认为定位是自己想做什么而不是竞争允许你做什么",
    ],
    output_implication: "候选方向必须明确回答：在竞争地图中它在什么位置？",
  },
  {
    id: "trout-differentiate-or-die",
    theory_source: "trout",
    name: "不差异化就死亡",
    principle: "在同质化市场中，差异化不是选择而是生存前提",
    decision_question: "如果消费者闭上眼睛想你的品牌，第一秒想到什么？",
    applicable_context: ["品类同质化严重", "头部品牌密集", "新进入者"],
    key_variables: ["差异化感知度", "差异化转述度", "差异化模仿难度"],
    decision_rules: [
      "在同质化的市场里，没有差异化的品牌等于不存在",
      "差异化必须存在于消费者感知中，而不是存在于产品参数中",
      "消费者说这家店和那家店差不多——这就是失败的信号",
      "差一个维度都比更好强——不同比好更重要",
    ],
    anti_patterns: [
      "把差异化理解为做得更好——消费者分不清谁更好",
      "做了差异但消费者感受不到",
      "做多个差异化等于没有差异化",
    ],
    output_implication: "候选方向必须有一个消费者可感知的差异化维度",
  },
  {
    id: "trout-war-defense",
    theory_source: "trout",
    name: "防御战原则",
    principle: "只有市场领导者才应该打防御战",
    decision_question: "这个品牌是市场领导者吗？它应该打防御战吗？",
    applicable_context: ["领导品牌", "品牌地位维护"],
    key_variables: ["市场份额领先度", "心智占有强度", "防御资源储备"],
    decision_rules: [
      "只有市场领导者才应该打防御战——其他人没有资格",
      "防御战的最佳策略是攻击自己——用新产品替代自己的旧产品",
      "领导者在防御时要随时准备封杀竞争对手的潜在攻击",
    ],
    anti_patterns: [
      "非领导品牌打防御战",
      "领导品牌在防御时选择不管而不是封杀",
      "领导品牌满足于现状不再自我攻击",
    ],
    output_implication: "非领导品牌不应选择防御型定位",
  },
  {
    id: "trout-war-offense",
    theory_source: "trout",
    name: "进攻战原则",
    principle: "进攻战的目标是领导者优势中的弱点",
    decision_question: "这个方向攻击的是领导者的真实弱点还是臆想的弱点？",
    applicable_context: ["挑战者品牌", "第二梯队品牌", "差异化切入"],
    key_variables: ["领导者弱点", "领导者可反击的空间", "攻击点的可持续性"],
    decision_rules: [
      "进攻战的目标是领导者优势中的弱点——不是任何弱点都可以",
      "如果领导者可以迅速弥补这个弱点，它就不是一个好的攻击点",
      "进攻者必须找到领导者优势中固有的弱点——这个弱点是领导者无法轻易改变的",
    ],
    anti_patterns: [
      "攻击领导者不重要的弱点",
      "攻击领导者可以迅速修复的弱点",
      "在多个方向上同时攻击",
    ],
    output_implication: "候选方向如果是挑战者定位，必须找到领导者优势中的固有弱点",
  },
  {
    id: "trout-war-flanking",
    theory_source: "trout",
    name: "侧翼战原则",
    principle: "侧翼战是在无争地带发起的突袭，是最适合新品牌的战术",
    decision_question: "这个方向是否进入了一个领导者无法或不愿意进入的市场？",
    applicable_context: ["新品牌", "资源有限", "寻找空位"],
    key_variables: ["无争地带的存在性", "侧翼突袭的突然性", "领导者的反应时间"],
    decision_rules: [
      "最好的侧翼战是进入一个完全无人竞争的地带",
      "侧翼战必须在战术上保持突然性",
      "侧翼成功后必须快速巩固成果，否则领导者会反击",
    ],
    anti_patterns: [
      "侧翼战变成了正面战",
      "侧翼成功后没有快速建立防御工事",
      "低估了领导者反击的速度和力度",
    ],
    output_implication: "新品牌最好的策略是侧翼战——找一个无争地带先站住脚",
  },
  {
    id: "trout-diff-attributes",
    theory_source: "trout",
    name: "从属性中找差异",
    principle: "差异化的核心来源是选择一个属性并独占它",
    decision_question: "这个品牌可以独占什么属性？",
    applicable_context: ["品类同质化", "寻找差异方向", "品牌定位"],
    key_variables: ["可占有的属性", "属性的消费者价值", "竞品对属性的占有度"],
    decision_rules: [
      "属性是差异化最直接的方式——最大、最新、最快、最贵、最便宜",
      "一个品牌只能占据一个属性——两个属性会互相削弱",
      "选择一个竞品没有占据的属性，然后持续强化它",
    ],
    anti_patterns: [
      "选择了一个竞品已经占据的属性",
      "试图同时占据两个属性",
      "选择了一个对消费者没有价值的属性",
    ],
    output_implication: "候选方向应围绕一个可独占的属性构建定位",
  },
  {
    id: "trout-first-association",
    theory_source: "trout",
    name: "第一联想法则",
    principle: "定位目标是需求出现时第一个被想起，不是被知道",
    decision_question: "消费者产生需求时会第一个想起你吗？",
    applicable_context: ["品类竞争激烈", "需建心智锚点", "多品牌同赛道"],
    key_variables: ["需求触发场景", "第一联想品牌", "关联强度"],
    decision_rules: [
      "需求产生时不会自然联想则定位未成功",
      "第一联想比知名度重要",
      "必须绑定具体需求场景",
    ],
    anti_patterns: [
      "高知名度不等于高心智占有率",
      "同时绑定多个不相关的联想",
      "联想是CEO想象的而非消费者认知的",
    ],
    output_implication: "第一联想方向做核心，其余都次要",
  },
  {
    id: "trout-simplicity",
    theory_source: "trout",
    name: "简单是终极武器",
    principle: "信息过载时代复杂信息无法进入心智，简单最有力量",
    decision_question: "能用最简单的话在3秒内说清楚吗？",
    applicable_context: ["品类信息复杂", "决策路径短", "传播资源有限"],
    key_variables: ["定位语长度复杂度", "复述准确度", "区分速度"],
    decision_rules: [
      "好的定位能用3秒说清3秒记住",
      "CEO需要一分钟解释的定位还不够简单",
      "去掉所有形容词只留名词和动词",
    ],
    anti_patterns: [
      "用抽象词汇显得有深度",
      "堆砌多个价值点",
      "书面语做定位语",
    ],
    output_implication: "定位语必须可被消费者3秒内复述",
  },
  {
    id: "trout-brand-trouble-signs",
    theory_source: "trout",
    name: "品牌危机的早期信号",
    principle: "大多数品牌危机在爆发前就有明确信号",
    decision_question: "这个品牌是否出现了品牌危机的早期信号？",
    applicable_context: ["品牌预警", "品牌诊断", "品牌复兴"],
    key_variables: ["销售下滑趋势", "品牌联想模糊", "竞品心智侵蚀"],
    decision_rules: [
      "品牌危机的第一个信号是销售下滑",
      "第二个信号是品牌联想开始模糊——消费者说不清你代表什么",
      "最危险的信号是内部认为品牌还好但外部已经变了",
    ],
    anti_patterns: [
      "用降价来应对品牌危机",
      "忽略品牌联想模糊的早期信号",
      "竞品心智侵蚀时反应太慢",
    ],
    output_implication: "品牌诊断时应检查是否有这些危机信号",
  },
  {
    id: "trout-simplicity-principle",
    theory_source: "trout",
    name: "简单原则",
    principle: "复杂的信息无法进入心智，简单是营销最强大的力量",
    decision_question: "这个定位的表述删掉一半字数后是否还成立？",
    applicable_context: ["定位表述优化", "传播素材", "品牌口号"],
    key_variables: ["信息量", "记忆成本", "转述难度"],
    decision_rules: [
      "一个好的定位应该能用一句话说清楚，能用3秒被记住",
      "如果定位需要三段话才能解释清楚，说明它还不够简单",
      "简单的标准是：一个初中生能听懂、能转述",
    ],
    anti_patterns: [
      "追求高级感而使用抽象词汇",
      "试图在定位语中包含所有优势",
      "把复杂的商业策略等同于复杂的定位表述",
    ],
    output_implication: "定位表述必须经过删半检验——删掉一半字数后还能说清吗？",
  },
];
