"""
core — M-MKT 核心模块

包含六维模型数据模型、评分引擎、知识资产、规则引擎和机会决策引擎。
"""

from .api import MKTEngine
from .runtime import AnalysisRequest, AnalysisResult, RuntimePipeline, ScoreAdjustment, TraceEvent
from .stages import (
    BuiltInScoringStrategy,
    ParseStage,
    RetrieveStage,
    RulesStage,
    ScoreStage,
    SolutionStage,
)
from .batch import BatchAnalyzer, BatchResult
from .dimension_definitions import (
    DIM_BRAND_MOMENTUM,
    DIM_COMPETITIVE_LANDSCAPE,
    DIM_CONSUMER_FIT,
    DIM_ENVIRONMENTAL_FIT,
    DIM_MARKET_CAPACITY,
    DIM_OPERATIONAL_FEASIBILITY,
    SIX_DIMENSIONS,
    build_opportunity_model,
    register_all,
)
from .engine import EntrepreneurProfile, OpportunityDecision, OpportunityEngine
from .exceptions import (
    AdapterError,
    DimensionError,
    IndicatorError,
    MMTKError,
    ModelError,
    ScoringError,
    SerializationError,
    ValidationError,
)
from .inference import InferenceConfig, InferenceResult, MKTInferencePipeline
from .knowledge import (
    ActionType,
    CaseStudy,
    CategoryKnowledge,
    CategoryLifecycle,
    CityProfile,
    CompetitionStructure,
    Condition,
    ConsumerScene,
    ConsumerStructure,
    DecisionRule,
    EntryAdvice,
    FailureMode,
    KnowledgeRetriever,
    LifecycleStage,
    MarketTag,
    Operator,
    OpportunityTag,
    PriceBand,
    RetrievalResult,
    Rule,
    RuleAction,
    RuleEngine,
    RuleResult,
    StrategyTag,
    find_price_band,
    find_scene,
)
from .knowledge.data import (
    ALL_CASES,
    ALL_CATEGORIES,
    ALL_CITIES,
    CATEGORY_MAP,
    CITY_MAP,
    DEFAULT_RULES,
)
from .models import Dimension, Indicator, ScoreLevel, SixDimensionModel
from .registry import DimensionRegistry, DimensionTemplate
from .scoring import ScoringEngine
from .serializer import ModelSerializer

__all__ = [
    "MKTEngine",
    "AnalysisRequest",
    "AnalysisResult",
    "RuntimePipeline",
    "ScoreAdjustment",
    "TraceEvent",
    "BuiltInScoringStrategy",
    "ParseStage",
    "RetrieveStage",
    "ScoreStage",
    "RulesStage",
    "SolutionStage",
    "BatchAnalyzer",
    "BatchResult",
    "SixDimensionModel",
    "Dimension",
    "Indicator",
    "ScoreLevel",
    "ScoringEngine",
    "DimensionRegistry",
    "DimensionTemplate",
    "ModelSerializer",
    "register_all",
    "build_opportunity_model",
    "SIX_DIMENSIONS",
    "DIM_MARKET_CAPACITY",
    "DIM_COMPETITIVE_LANDSCAPE",
    "DIM_CONSUMER_FIT",
    "DIM_OPERATIONAL_FEASIBILITY",
    "DIM_BRAND_MOMENTUM",
    "DIM_ENVIRONMENTAL_FIT",
    "CategoryKnowledge",
    "CategoryLifecycle",
    "ConsumerStructure",
    "CompetitionStructure",
    "FailureMode",
    "EntryAdvice",
    "LifecycleStage",
    "CaseStudy",
    "DecisionRule",
    "CityProfile",
    "Condition",
    "Operator",
    "RuleAction",
    "ActionType",
    "Rule",
    "RuleResult",
    "RuleEngine",
    "MarketTag",
    "OpportunityTag",
    "StrategyTag",
    "PriceBand",
    "ConsumerScene",
    "find_price_band",
    "find_scene",
    "KnowledgeRetriever",
    "RetrievalResult",
    "MKTInferencePipeline",
    "InferenceConfig",
    "InferenceResult",
    "ALL_CATEGORIES",
    "CATEGORY_MAP",
    "ALL_CASES",
    "ALL_CITIES",
    "CITY_MAP",
    "DEFAULT_RULES",
    "OpportunityEngine",
    "OpportunityDecision",
    "EntrepreneurProfile",
    "MMTKError",
    "ModelError",
    "DimensionError",
    "IndicatorError",
    "ValidationError",
    "AdapterError",
    "ScoringError",
    "SerializationError",
]
