/**
 * 大师经验库 — 20+ 条经营智慧
 *
 * 30年餐饮经营智慧
 * 覆盖：创业、成本、品牌、品类、选址、扩张、产品、竞争、团队、营销、财务、危机
 */

import type { MasterExperience } from "../types";

export const MASTER_EXPERIENCES: MasterExperience[] = [
  {
    id: "MK-MASTER-0001",
    topic: "创业时机",
    question: "什么时候不应该开店？",
    wisdom: "如果只有产品能力，没有获客能力和品牌能力，不要做大店。",
    scenario: "首次创业",
    reasoning: "产品只是基础，获客和品牌才是生存关键。大店需要更多客流支撑，没有获客能力意味着无法持续。",
    risks: ["现金流断裂", "获客成本过高", "品牌认知建立慢"],
    application: "先做小店验证模型，积累品牌和获客能力后再扩张",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.95,
  },
  {
    id: "MK-MASTER-0002",
    topic: "成本认知",
    question: "为什么很多老板死在控制成本？",
    wisdom: "很多老板死在控制成本，而不是成本高。",
    scenario: "成本管理",
    reasoning: "过度控制成本会牺牲品质和体验，导致客户流失。正确的做法是优化成本结构，而不是简单削减。",
    risks: ["品质下降", "客户流失", "口碑变差"],
    application: "成本控制要在保证品质的前提下进行，找到平衡点",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0003",
    topic: "高端定位",
    question: "什么时候可以做高端？",
    wisdom: "没有品牌资产不要做高端。高端不是价格高，是品牌认知高。",
    scenario: "品牌定位",
    reasoning: "高端餐饮需要品牌支撑。没有品牌，高价格只会吓跑客户，不会带来高端认知。",
    risks: ["客户不认可", "投资回报差", "被迫降价"],
    application: "先在中端建立口碑，积累品牌资产，再逐步升级",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.95,
  },
  {
    id: "MK-MASTER-0004",
    topic: "网红品类",
    question: "网红品类能做吗？",
    wisdom: "网红是起点，不是终点。品牌生命周期=复购率×口碑。",
    scenario: "品类选择",
    reasoning: "网红品类带来流量，但流量不等于复购。没有复购，品牌就会昙花一现。",
    risks: ["热度消退", "竞争激烈", "复购率低"],
    application: "如果选择网红品类，必须建立复购壁垒（产品、服务、体验）",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0005",
    topic: "选址判断",
    question: "租金便宜是好位置吗？",
    wisdom: "租金低不是优势，有效客流×消费能力×复购才是核心。",
    scenario: "选址决策",
    reasoning: "租金只是成本变量，真正重要的是位置带来的价值。低租金往往意味着低客流或低消费力。",
    risks: ["客流不足", "消费力低", "复购差"],
    application: "评估位置要看有效客流、消费能力、复购潜力，而不是只看租金",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.95,
  },
  {
    id: "MK-MASTER-0006",
    topic: "扩张时机",
    question: "什么时候可以开第二家店？",
    wisdom: "没有标准化就扩张是找死。",
    scenario: "扩张决策",
    reasoning: "第一家店成功可能是运气，标准化才能复制。没有标准化，第二家店大概率失败。",
    risks: ["品质不稳定", "管理失控", "资源分散"],
    application: "先建立标准化体系（产品、流程、培训、供应链），验证可复制性后再扩张",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0007",
    topic: "产品认知",
    question: "好吃就能成功吗？",
    wisdom: "好吃是必要条件，不是充分条件。",
    scenario: "产品策略",
    reasoning: "餐饮成功需要产品+场景+体验+运营的综合能力。只有产品好，其他不行，也会失败。",
    risks: ["忽略其他要素", "投资过度在产品", "忽视获客"],
    application: "产品是基础，但要同时关注场景、体验、获客、成本",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0008",
    topic: "竞争策略",
    question: "怎么应对竞争？",
    wisdom: "不要打价格战，要打价值战。",
    scenario: "竞争策略",
    reasoning: "价格战两败俱伤，价值战才能建立壁垒。差异化是避开竞争的最好方式。",
    risks: ["利润下降", "品质下降", "恶性循环"],
    application: "找到差异化点，建立独特价值，而不是降价竞争",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },

  // ═══════════════════════════════════════════
  // 新增经验 (0009-0022)
  // ═══════════════════════════════════════════
  {
    id: "MK-MASTER-0009",
    topic: "合伙人",
    question: "餐饮合伙要注意什么？",
    wisdom: "餐饮合伙，能力互补比资金互补更重要。",
    scenario: "合伙创业",
    reasoning: "餐饮需要产品、运营、营销等多方面能力。合伙人之间能力互补，才能覆盖所有关键环节。",
    risks: ["能力重叠", "分工不清", "决策冲突"],
    application: "选择合伙人要看能力互补性，签订明确的合伙协议",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0010",
    topic: "菜单设计",
    question: "菜单多少个菜合适？",
    wisdom: "菜单不是越多越好。40-50个SKU是大多数餐厅的最优解。",
    scenario: "产品策略",
    reasoning: "菜品过多导致：采购复杂、库存压力大、品质不稳定、顾客选择困难。精简菜单才能聚焦。",
    risks: ["品质不稳定", "库存浪费", "选择困难"],
    application: "精简菜单，聚焦招牌菜和高毛利菜品",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0011",
    topic: "外卖",
    question: "外卖占比多少健康？",
    wisdom: "外卖占比超过50%就要警惕。平台依赖是慢性毒药。",
    scenario: "渠道策略",
    reasoning: "外卖平台抽成15-25%，大幅压缩利润。过度依赖平台，一旦政策变化或流量下降，风险极大。",
    risks: ["平台依赖", "利润压缩", "流量不可控"],
    application: "堂食为主，外卖为辅。建立自有渠道（小程序、社群）",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0012",
    topic: "员工管理",
    question: "怎么留住好员工？",
    wisdom: "留人靠的不是工资，是成长和尊重。",
    scenario: "团队管理",
    reasoning: "餐饮行业流动性大，但好员工最看重的是成长空间和被尊重的感觉。单纯加薪效果有限。",
    risks: ["人员流失", "培训成本", "服务品质波动"],
    application: "建立晋升通道、培训体系、尊重文化",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0013",
    topic: "营销",
    question: "餐饮营销的核心是什么？",
    wisdom: "最好的营销是让顾客帮你传播。口碑>广告>促销。",
    scenario: "营销策略",
    reasoning: "餐饮是体验型消费，口碑是最有效的获客方式。广告和促销只能带来首次消费，口碑才能带来复购。",
    risks: ["营销成本高", "效果不可持续", "依赖流量"],
    application: "把营销预算投入产品和体验，让顾客自发传播",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0014",
    topic: "财务",
    question: "餐饮老板最该关注什么财务指标？",
    wisdom: "现金流比利润更重要。很多店死在现金流断裂，而不是亏损。",
    scenario: "财务管理",
    reasoning: "餐饮现金流波动大（季节、竞争、突发事件）。利润是纸面数字，现金流才是生存保障。",
    risks: ["现金流断裂", "无法支付供应商", "被迫关店"],
    application: "至少预留3-6个月运营资金，关注现金流而非只看利润",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.9,
  },
  {
    id: "MK-MASTER-0015",
    topic: "危机",
    question: "遇到危机怎么办？",
    wisdom: "危机时最重要的不是省钱，是保持核心团队。",
    scenario: "危机管理",
    reasoning: "危机终会过去，但核心团队一旦流失，恢复期会更长。保留核心团队，才能在危机后快速恢复。",
    risks: ["核心人员流失", "恢复期延长", "竞争力下降"],
    application: "危机时削减非核心开支，保留核心团队",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0016",
    topic: "供应链",
    question: "供应链管理的关键是什么？",
    wisdom: "供应链不是找最便宜的，是找最稳定的。",
    scenario: "供应链管理",
    reasoning: "餐饮品质的一致性依赖供应链的稳定性。便宜但不稳定的供应商，会导致品质波动和断货风险。",
    risks: ["品质波动", "断货", "成本不可控"],
    application: "选择2-3家稳定供应商，建立长期合作关系",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0017",
    topic: "创新",
    question: "餐饮需要创新吗？",
    wisdom: "创新要围绕顾客需求，不是老板的自嗨。",
    scenario: "产品创新",
    reasoning: "很多老板的创新是自己的想法，而不是顾客的需求。创新要基于数据和反馈，而不是直觉。",
    risks: ["脱离市场", "资源浪费", "顾客不买账"],
    application: "创新前先调研，小范围测试，根据反馈迭代",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0018",
    topic: "品牌",
    question: "品牌是什么？",
    wisdom: "品牌不是logo和装修，是顾客对你的认知。",
    scenario: "品牌建设",
    reasoning: "品牌是顾客心智中的位置。装修可以抄，logo可以仿，但顾客的认知是唯一的。",
    risks: ["品牌认知模糊", "差异化不足", "溢价能力弱"],
    application: "聚焦一个核心价值，在顾客心智中建立独特位置",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0019",
    topic: "数字化",
    question: "餐饮需要数字化吗？",
    wisdom: "数字化是工具，不是目的。先有好的产品和运营，数字化才能放大价值。",
    scenario: "数字化转型",
    reasoning: "数字化可以提升效率和体验，但不能替代产品和运营。很多餐厅投入大量数字化，但基础问题没解决。",
    risks: ["投入产出比低", "系统复杂", "忽视基础"],
    application: "先解决产品和运营问题，再用数字化提升效率",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.75,
  },
  {
    id: "MK-MASTER-0020",
    topic: "心态",
    question: "餐饮创业最重要的是什么心态？",
    wisdom: "餐饮是马拉松，不是百米冲刺。急不得。",
    scenario: "创业心态",
    reasoning: "餐饮需要时间积累口碑、磨合团队、优化产品。急于求成往往导致决策失误。",
    risks: ["急于扩张", "忽视品质", "决策冲动"],
    application: "设定合理预期，做好长期投入的准备",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
  {
    id: "MK-MASTER-0021",
    topic: "选址",
    question: "商场店和社区店怎么选？",
    wisdom: "商场店靠品牌，社区店靠复购。没有品牌力，不要进商场。",
    scenario: "选址决策",
    reasoning: "商场需要品牌引流，没有品牌力的餐厅在商场会被淹没。社区店靠复购，更适合新品牌。",
    risks: ["商场租金高", "竞争激烈", "品牌力不足"],
    application: "新品牌先做社区店积累口碑，有品牌力后再进商场",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.85,
  },
  {
    id: "MK-MASTER-0022",
    topic: "定价",
    question: "怎么定价？",
    wisdom: "定价不是成本加利润，是价值感知。",
    scenario: "定价策略",
    reasoning: "顾客不关心你的成本，只关心获得的价值。定价要基于顾客感知价值，而不是成本加成。",
    risks: ["定价过高无人问津", "定价过低利润不足", "价值感不匹配"],
    application: "研究目标客群的支付意愿，设计价值感",
    master: "30年餐饮老兵", source: "经验库", confidence: 0.8,
  },
];

/**
 * 查询大师经验
 */
export function queryMasterWisdom(
  topic: string,
  experiences: MasterExperience[] = MASTER_EXPERIENCES
): MasterExperience[] {
  return experiences.filter(exp => {
    return (
      exp.topic.includes(topic) ||
      exp.scenario.includes(topic) ||
      exp.question.includes(topic)
    );
  }).sort((a, b) => b.confidence - a.confidence);
}
