/**
 * M-PNT 矩阵 — 案例资产库（V2 扩展）
 */
import type { CaseAsset } from "./types";

export const caseAssets: CaseAsset[] = [
  {
    id: "case-haidilao",
    brand_name: "海底捞",
    category: "火锅",
    city_context: "全国",
    market_stage: "成熟期",
    project_stage: "品牌跃升",
    initial_problem: "火锅品类极度同质化，消费者无法区分品牌",
    resource_condition: "早期有限，团队有服务经验",
    competition_context: "心智被正宗川味占据",
    candidate_positions: ["最好川味火锅", "服务最好火锅", "年轻人火锅"],
    final_position: "服务最好火锅——以极致服务建立品类区隔",
    why_choose: "服务是火锅品类中无人占据的心智空位",
    why_not_others: "最好川味是正面冲突，年轻人火锅太泛",
    differentiation_design: "等位美甲拉面生日惊喜等极致服务触点",
    execution_actions: ["服务即产品", "招聘选服务意识", "每个触点设计成可转述的故事"],
    market_feedback: "服务成为第一联想超越口味本身",
    result_summary: "品类区隔经典案例：差异化不在锅里在锅外",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "同质化品类可在非产品维度找到空位",
    reusable_principles: ["换维度竞争", "服务文化比菜品配方难抄袭", "消费者口碑比广告有效"],
    risk_lessons: ["服务差异靠人管理成本极高", "不学文化只学服务会消失"],
    theory_tags: ["trout", "ye_maozhong"],
  },
  {
    id: "case-chayan",
    brand_name: "茶颜悦色",
    category: "茶饮",
    city_context: "长沙",
    market_stage: "成长期",
    project_stage: "品牌创立",
    initial_problem: "茶饮市场已被喜茶奈雪CoCo占满",
    resource_condition: "初创资金有限，团队有文创背景",
    competition_context: "高端=喜茶/茶+包=奈雪/性价比=CoCo",
    candidate_positions: ["更好的茶饮", "长沙本地茶饮", "中国风茶饮"],
    final_position: "中国风茶饮——以中式美学建立品类第一",
    why_choose: "西式日式审美主流中中国风是显眼心智空位",
    why_not_others: "更好无心智位置，本地天花板太低",
    differentiation_design: "古典logo诗词文案坚果奶油顶永久求偿权",
    execution_actions: ["深耕长沙不急于扩张", "每杯茶配诗词成社交素材", "永久求偿权建信任", "中式庭院空间"],
    market_feedback: "长沙必打卡品牌排队破纪录",
    result_summary: "利用文化符号在心智中建立第一位置",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "文化表达是被忽视的差异化维度",
    reusable_principles: ["换维度占不同而非更好", "文化符号难被模仿", "区域第一也是第一"],
    risk_lessons: ["出长沙后品牌力需验证", "国风需持续投入"],
    theory_tags: ["ries", "trout"],
  },
  {
    id: "case-wanglaoji",
    brand_name: "王老吉",
    category: "凉茶",
    city_context: "全国",
    market_stage: "成长期",
    project_stage: "品牌重塑",
    initial_problem: "凉茶地方品类全国无认知",
    resource_condition: "加多宝有强大渠道能力",
    competition_context: "可乐/茶饮/功能饮料三分天下无凉茶位置",
    candidate_positions: ["正宗广东凉茶", "健康草本饮料", "怕上火喝王老吉"],
    final_position: "怕上火喝王老吉——全民焦虑+高频场景绑定",
    why_choose: "上火是全民焦虑凉茶去火有基础认知",
    why_not_others: "正宗广东太窄健康饮料太宽",
    differentiation_design: "红色包装怕上火心理暗示绑定火锅烧烤场景",
    execution_actions: ["广告全国轰炸", "绑定火锅烧烤夜宵", "红色罐装视觉霸盘", "统一零售价"],
    market_feedback: "最成功广告语之一年销超200亿",
    result_summary: "冲突营销教科书：焦虑+场景+方案=条件反射",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "最好的定位是利用已有焦虑而非创造新概念",
    reusable_principles: ["冲突是消费者本就在意的", "定位语=条件反射触发器", "高频场景绑定效率最高"],
    risk_lessons: ["单一功能有天花板", "品牌延伸困难"],
    theory_tags: ["ye_maozhong", "ries"],
  },
  {
    id: "case-guyue",
    brand_name: "古茗茶饮",
    category: "茶饮",
    city_context: "浙江台州",
    market_stage: "成长后期",
    project_stage: "定位清晰化",
    initial_problem: "中低端茶饮品牌心智模糊无差异",
    resource_condition: "区域供应链扎实有茶叶背景",
    competition_context: "高端喜茶/中低端CoCo一点点/极致低价蜜雪",
    candidate_positions: ["更好的奶茶", "水果茶专家", "每天一杯喝不腻"],
    final_position: "每天一杯喝不腻+区域密集深耕策略",
    why_choose: "不追网红化而做日常高频复购",
    why_not_others: "更好无位置水果茶门槛不高",
    differentiation_design: "水果加茶清爽不贵社区小店模型",
    execution_actions: ["区域深耕密度优先", "不投全国广告", "比喜茶便宜30-50%", "自建供应链控品质"],
    market_feedback: "逆势增长成为中国门店规模最大的茶饮品牌之一",
    result_summary: "验证聚焦理论的区域版：日常首选比网红打卡更可持续",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "日常首选比网红打卡更有长期价值",
    reusable_principles: ["先区域第一再全国第一", "中端定位=日常首选而非比高端便宜", "高频复购重于网红流量"],
    risk_lessons: ["区域策略品牌势能输全国", "不投传播是双刃剑"],
    theory_tags: ["ries", "ye_maozhong"],
  },
  {
    id: "case-xian-noodle",
    brand_name: "张小花骨汤面（化名）",
    category: "面馆",
    city_context: "西安",
    market_stage: "成熟期",
    project_stage: "从零创业",
    initial_problem: "西安面食极度饱和，竞品全打老字号传统",
    resource_condition: "预算仅20万，无品牌背景",
    competition_context: "老字号占据心智高地",
    candidate_positions: ["正宗西安面", "年轻人的面馆", "骨汤不勾兑喝完不口渴"],
    final_position: "骨汤不勾兑喝完不口渴——攻击竞品弱点",
    why_choose: "预算极少时攻击竞品弱点是最低成本策略",
    why_not_others: "正宗打不过老字号，年轻人不是场景",
    differentiation_design: "透明厨房展示骨汤熬制不勾兑承诺",
    execution_actions: ["门头打不用勾兑汤", "展示真骨头", "抖音吃面不口渴挑战", "汤底免费续建信任"],
    market_feedback: "开业引发本地讨论6个月盈亏平衡",
    result_summary: "极低预算用小博大验证侧翼战+冲突论",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "预算越少定位越要锋利",
    reusable_principles: ["攻击竞品弱点是零成本策略", "最好差异来自竞品不敢说的弱点", "不做什么比做什么易传播"],
    risk_lessons: ["攻击策略会引来反击", "真材实料否则口碑崩塌"],
    theory_tags: ["trout", "ye_maozhong"],
  },
  {
    id: "case-chongqing-daily",
    brand_name: "味道重庆（化名）",
    category: "川菜",
    city_context: "重庆",
    market_stage: "红海",
    project_stage: "品牌升级",
    initial_problem: "重庆菜品牌全打正宗无人做场景差异",
    resource_condition: "8家门店年营收3000万",
    competition_context: "全部讲味道正宗无其他差异",
    candidate_positions: ["重庆第一江湖菜", "重庆人的家庭食堂", "游客必吃榜"],
    final_position: "重庆人的家庭食堂——绑定本地家庭日常场景",
    why_choose: "竞品全做网红必吃无人做日常场景是空位",
    why_not_others: "第一自封无法验证游客依赖旅游周期",
    differentiation_design: "家庭套餐设计社区定价2-3人份量",
    execution_actions: ["调低客单价至家庭区间", "套餐按2-3人设计", "社区口碑不做网红", "周日家庭特惠"],
    market_feedback: "复购率45%远超重庆餐饮平均水平",
    result_summary: "红海通过场景切割找到蓝海",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "红海最佳策略不是更好是找日常空位",
    reusable_principles: ["日常是最好空位", "场景定位复购率远高于品类定位", "本地日常比游客打卡可持续"],
    risk_lessons: ["不网红传播慢", "需熬过冷启动期"],
    theory_tags: ["trout", "ries"],
  },
  {
    id: "case-feiyue-dumpling",
    brand_name: "飞跃饺子",
    category: "饺子",
    city_context: "长沙",
    market_stage: "成熟期",
    project_stage: "品牌升级",
    initial_problem: "饺子品牌同质化严重消费者觉得都差不多",
    resource_condition: "预算60万团队4人有中央厨房",
    competition_context: "竞品全定位手工水饺东北风味无差异",
    candidate_positions: ["长沙最好吃饺子", "每天现拌馅", "年轻人的饺子局"],
    final_position: "年轻人的饺子局——夜间社交场景切割",
    why_choose: "饺子有家的味道也容易老气夜间社交场景是竞品空白",
    why_not_others: "最好吃无法验证现拌馅对面都在用",
    differentiation_design: "深夜食堂氛围单人双人套餐精酿搭配社交动线",
    execution_actions: ["暖色改冷调工业风", "菜单瘦身40%", "开夜宵时段", "主推年轻人的饺子局"],
    market_feedback: "夜间占比45%客单价升22%复购高15%",
    result_summary: "以场景切割在全品类中找到差异化空位",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "同质化品类最佳差异不是产品是场景",
    reusable_principles: ["产品同质时场景切割优于产品升级", "夜间经济是年轻化用户池", "场景定位需配套门店体验"],
    risk_lessons: ["晚间客流需3个月爬坡", "场景过窄可能丢失午餐客群"],
    theory_tags: ["trout", "ye_maozhong"],
  },
  {
    id: "case-laohu-hotpot",
    brand_name: "老街老火锅",
    category: "火锅",
    city_context: "重庆",
    market_stage: "红海",
    project_stage: "筹备开店",
    initial_problem: "重庆火锅极度饱和头部品牌心智固化",
    resource_condition: "预算200万有底料配方无连锁经验",
    competition_context: "海底捞服务/周师兄毛肚/珮姐回家路线",
    candidate_positions: ["正宗重庆老火锅", "一人食精致火锅", "火锅小酒馆"],
    final_position: "一个人也要好好吃火锅——一人食场景切割",
    why_choose: "一人食是火锅品类未被占稳的空位单身经济趋势明确",
    why_not_others: "正宗与头部正面冲突酒馆执行不支持",
    differentiation_design: "单人小锅高吧台套餐化一人食环境",
    execution_actions: ["吧台单人座60%", "3款一人食套餐", "8分钟上齐", "主攻下班后一人食"],
    market_feedback: "6个月盈亏平衡一人食占比70%复购32%",
    result_summary: "红海中找到场景空位验证区隔理论实战价值",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "即使红海只要切出真实场景空位仍有进入窗口",
    reusable_principles: ["饱和市场找场景空位不打正面战", "一人食前提是不尴尬不浪费不等", "品类越成熟场景切割越锋利"],
    risk_lessons: ["午市上座率不足", "翻台压力大厨房动线需提前设计"],
    theory_tags: ["trout", "ye_maozhong"],
  },
  {
    id: "case-failure-bread",
    brand_name: "巴黎贝甜（化名·中国案例）",
    category: "烘焙",
    city_context: "上海",
    market_stage: "成熟期",
    project_stage: "品牌重塑",
    initial_problem: "烘焙品牌无差异消费者看距离选店",
    resource_condition: "50家店预算200万",
    competition_context: "好利来蛋糕/85°C咖啡面包/幸福西饼线上",
    candidate_positions: ["最好吃面包", "每日新鲜现烤", "不卖隔夜面包"],
    final_position: "不卖隔夜面包——新鲜承诺",
    why_choose: "听起来有冲突感可打击竞品潜规则",
    why_not_others: "最好吃和现烤都是通用话术",
    differentiation_design: "晚8点折扣清货透明厨房当日清货系统",
    execution_actions: ["清货系统投入", "打折处理当日未售出", "不卖隔夜传播"],
    market_feedback: "初期有话题但三方矛盾暴露：打折降品牌感知/晚7点后无货可选/损耗吞噬利润",
    result_summary: "定位看似锋利执行中盈利模型崩溃：定位承诺与盈利模式冲突",
    success_or_failure: "failure",
    quality_tier: "silver_case",
    mental_takeaway: "定位承诺须在品牌产品和盈利三个方向上都成立",
    reusable_principles: ["定位承诺必须经成本倒推检验", "不做什么承诺比做什么更难兑现", "消费者对价格比对承诺更敏感"],
    risk_lessons: ["打折破坏正价购买体验", "执行前必须做成本模型测算", "不要选择伤害盈利模型的定位"],
    theory_tags: ["ye_maozhong", "trout"],
  },
  {
    id: "case-xiangpiaopiao",
    brand_name: "香飘飘",
    category: "奶茶饮品",
    city_context: "全国",
    market_stage: "成长期",
    project_stage: "品牌重塑",
    initial_problem: "杯装奶茶被瓶装/门店奶茶挤压品类萎缩趋势",
    resource_condition: "全国渠道与供应链优势，有限传播预算",
    competition_context: "门店奶茶占体验心智，瓶装即饮占便利心智",
    candidate_positions: ["更好喝的杯装奶茶", "随时随地喝好奶茶", "小饿小困喝香飘飘"],
    final_position: "小饿小困喝香飘飘——场景绑定+冲突制造",
    why_choose: "小饿小困是高频真实场景，门店/瓶装无法覆盖该场景",
    why_not_others: "更好无位置，随时随地太宽",
    differentiation_design: "杯装场景化（办公室/宿舍/加班），冲泡体验仪式感",
    execution_actions: ["场景广告高频投放", "杯体设计暖心文案", "绑定小饿小困场景", "冲泡型口感优化"],
    market_feedback: "小饿小困成为香飘飘专属场景联想，品牌逆势回升",
    result_summary: "场景定位+冲突制造拯救成熟品类",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "场景绑定+冲突句=条件反射式定位",
    reusable_principles: ["高频场景比品类定位更锋利", "小饿小困是人人有但未被占的场景", "好定位让竞品说不出同样的话"],
    risk_lessons: ["场景过窄可能损失主品类优势", "冲泡方式需跟上消费习惯变迁"],
    theory_tags: ["ye_maozhong", "ries", "trout"],
  },
  {
    id: "case-haiyue-home",
    brand_name: "海跃（化名）社区食堂",
    category: "社区餐饮",
    city_context: "上海浦东",
    market_stage: "成熟期红海",
    project_stage: "品牌创立",
    initial_problem: "社区餐饮同质化严重，大家都是附近随便吃吃的选择",
    resource_condition: "预算50万，团队有烹饪背景",
    competition_context: "周边社区店多打实惠/量大/家常，无品牌差异",
    candidate_positions: ["上海最好吃的社区食堂", "海跃就是你家厨房", "每周七天不重样"],
    final_position: "海跃就是你家厨房——超级符号+文化母体寄生",
    why_choose: "家=最强文化母体，厨房=温馨符号，把社区食堂寄生在家的文化里",
    why_not_others: "最好吃无法验证，不重样执行成本高",
    differentiation_design: "店内像家一样温暖，开放厨房+家庭式餐具+家的味道菜品",
    execution_actions: ["门头设计温暖灯光和家的符号", "开放厨房让客人看到做饭过程", "碗筷用家用非标准化", "主打妈妈味道系列"],
    market_feedback: "复购率远超同类社区餐饮，成为社区必吃选择",
    result_summary: "文化母体寄生在社区餐饮的成功案例",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "最强的符号来自最普世的文化母体",
    reusable_principles: ["家是最强文化母体", "超级符号降低识别成本", "高频场景×文化母体=定位复利"],
    risk_lessons: ["文化符号需持续维护一致性", "扩张时家的温度感难规模化"],
    theory_tags: ["ye_maozhong", "ries", "trout"],
  },
  {
    id: "case-shanghai-bistro-growth",
    brand_name: "小酒馆烟火气（化名）",
    category: "小酒馆",
    city_context: "上海",
    market_stage: "成长期",
    project_stage: "品牌增长",
    initial_problem: "小酒馆赛道拥挤，各品牌同质化严重，增长停滞",
    resource_condition: "已有3家门店，年营收800万",
    competition_context: "大多小酒馆走网红风/工业风/日式风，同质化竞争",
    candidate_positions: ["上海最好的小酒馆", "下班后的第二客厅", "年轻人的烟火气"],
    final_position: "下班后的第二客厅——增长飞轮绑定日常复购",
    why_choose: "绑定下班后高频场景，以复购带动飞轮增长",
    why_not_others: "最好无法验证，烟火气已泛化",
    differentiation_design: "像客厅一样舒适，会员制绑定复购，下班场景锚定",
    execution_actions: ["设定下班后的客厅体验动线", "会员储值+积分飞轮", "每周主题活动促进复购", "场景套餐按下班时段设计"],
    market_feedback: "复购率提升40%，单店LTV增长2倍",
    result_summary: "增长飞轮驱动小酒馆品牌持续增长",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "增长飞轮的轴心要选高频可复购动作",
    reusable_principles: ["增长不是烧钱是飞轮设计", "高频场景是增长最佳杠杆", "会员飞轮比流量飞轮更可持续"],
    risk_lessons: ["增长飞轮依赖复购设计", "场景绑定过死会影响非高峰时段"],
    theory_tags: ["ye_maozhong", "ries", "trout"],
  },
  {
    id: "case-qipai-menswear",
    brand_name: "柒牌男装",
    category: "男装",
    city_context: "全国",
    market_stage: "成长期",
    project_stage: "品牌传播",
    initial_problem: "男装品类同质化，消费者说不清品牌差异",
    resource_condition: "有代言人资源与央视投放能力",
    competition_context: "竞品多打成功/商务/时尚，少触达男性自我要求",
    candidate_positions: ["成功男人的选择", "商务精英男装", "男人就应该对自己狠一点"],
    final_position: "男人就应该对自己狠一点——绑定男性自我要求的心理冲突",
    why_choose: "击中男性在事业与自我要求之间的内在冲突，口语化强、可重复",
    why_not_others: "成功/商务是竞品红海，缺乏情绪穿透力",
    differentiation_design: "代言人演绎狠劲与自律，口号成为社会流行语",
    execution_actions: ["央视高频投放同一口号", "终端物料统一狠一点表达", "绑定奋斗场景而非纯产品功能"],
    market_feedback: "口号成为全民记忆，品牌知名度与好感度大幅提升",
    result_summary: "冲突营销经典：心理层冲突+口语化口号+重复投放=品牌资产",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "心理冲突比功能卖点更易形成全民记忆",
    reusable_principles: ["冲突三层次之心理层", "口语是最高级传播语言", "重复同一口号积累资产"],
    risk_lessons: ["口号与产品体验脱节会反噬", "时代语境变化需迭代表达"],
    theory_tags: ["ye_maozhong"],
  },
  {
    id: "case-dahongying",
    brand_name: "大红鹰",
    category: "卷烟",
    city_context: "华东",
    market_stage: "成熟期",
    project_stage: "品牌塑造",
    initial_problem: "卷烟品牌需要强烈符号化记忆在限制传播条件下",
    resource_condition: "区域强势渠道与视觉识别预算",
    competition_context: "同类品牌多打地域或品质，缺乏符号化冲突",
    candidate_positions: ["浙江人的烟", "高档卷烟", "胜利之鹰"],
    final_position: "胜利之鹰——鹰符号+胜利心理冲突",
    why_choose: "鹰是强势视觉锤，胜利关联男性征服心理",
    why_not_others: "地域太窄，高档无区隔",
    differentiation_design: "鹰图腾视觉体系，包装与传播统一胜利意象",
    execution_actions: ["鹰符号全渠道统一", "绑定胜利场景", "口号与视觉锤强绑定"],
    market_feedback: "区域市场形成强烈品牌识别，鹰成为第一联想",
    result_summary: "符号化冲突在受限品类中仍能建立记忆",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "视觉锤+心理冲突可在传播受限品类中占位",
    reusable_principles: ["触发词/符号法则", "创意就是权力", "广告是品牌资产投资"],
    risk_lessons: ["健康政策变化影响品类", "符号需与合规边界平衡"],
    theory_tags: ["ye_maozhong"],
  },
  {
    id: "case-ambrosial",
    brand_name: "安慕希",
    category: "希腊风味酸奶",
    city_context: "全国",
    market_stage: "成长期",
    project_stage: "品类创新",
    initial_problem: "常温酸奶红海，低温酸奶有品类认知但便利性差",
    resource_condition: "伊利渠道与研发资源",
    competition_context: "常温酸奶=普通/低价，低温=新鲜但需冷链",
    candidate_positions: ["更好喝的酸奶", "常温酸奶领导", "希腊风味酸奶"],
    final_position: "希腊风味酸奶——开创新子品类并占第一",
    why_choose: "希腊风味是消费者可理解的新分支，安慕希=该分支第一",
    why_not_others: "更好无区隔，常温领导已有强势竞品",
    differentiation_design: "浓醇口感+希腊符号+明星代言+渠道密集",
    execution_actions: ["定义并命名子品类", "全渠道铺货", "持续希腊风味传播", "产品形态差异化"],
    market_feedback: "成为希腊风味酸奶代名词，销售额长期领先",
    result_summary: "品类分化+冲突占位：新分支第一比旧品类更好更有效",
    success_or_failure: "success",
    quality_tier: "gold_case",
    mental_takeaway: "开创新品类名并重复占位是冲突与心智的交集",
    reusable_principles: ["品类树原理", "成为第一差异化", "中国式创新"],
    risk_lessons: ["跟风竞品稀释子品类", "需持续产品迭代支撑占位"],
    theory_tags: ["ye_maozhong", "ries", "trout"],
  },
  {
    id: "case-zhujiang-chunsheng",
    brand_name: "珠江纯生",
    category: "啤酒",
    city_context: "华南",
    market_stage: "成熟期",
    project_stage: "产品定位",
    initial_problem: "啤酒品类消费者难感知工艺差异",
    resource_condition: "珠江啤酒区域品牌基础",
    competition_context: "竞品多打爽/纯/生概念混乱",
    candidate_positions: ["更好喝的啤酒", "广东人的啤酒", "纯生啤酒专家"],
    final_position: "纯生——以工艺名占位新鲜冲突",
    why_choose: "纯生是消费者可理解的工艺差异，绑定新鲜vs普通熟啤冲突",
    why_not_others: "地域限制大，更好无标准",
    differentiation_design: "纯生工艺可视化，绑定畅饮新鲜场景",
    execution_actions: ["纯生产品线聚焦", "区域渠道深耕", "新鲜畅饮场景绑定"],
    market_feedback: "华南市场纯生认知与珠江强关联",
    result_summary: "工艺差异化制造可感知冲突，区域做深",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "制造方式差异化可转化为消费者语言",
    reusable_principles: ["制造方式差异化", "场景是冲突触发器", "市场专长差异化"],
    risk_lessons: ["全国化时纯生概念竞品已跟进", "工艺差异需持续教育"],
    theory_tags: ["ye_maozhong", "trout"],
  },
  {
    id: "case-luning-shoes",
    brand_name: "路宁特",
    category: "运动鞋",
    city_context: "全国",
    market_stage: "成长期",
    project_stage: "品牌传播",
    initial_problem: "运动鞋市场国际品牌占心智，本土品牌缺情感连接",
    resource_condition: "有体育营销与代言人资源",
    competition_context: "国际牌=专业/潮流，本土多打性价比",
    candidate_positions: ["专业运动装备", "国民运动鞋", "走得更远"],
    final_position: "走得更远——绑定运动与人生进阶的心理冲突",
    why_choose: "超越产品功能，击中消费者自我超越渴望",
    why_not_others: "专业无法与国际品牌硬刚，性价比无记忆",
    differentiation_design: "代言人故事+走得更远口号+赛事绑定",
    execution_actions: ["口号多年重复", "体育事件借势", "产品线与进阶叙事一致"],
    market_feedback: "口号成为品牌核心资产，运动场景强关联",
    result_summary: "心理层冲突+长期重复建立本土运动品牌占位",
    success_or_failure: "success",
    quality_tier: "silver_case",
    mental_takeaway: "走得远比跑得快更易引发共鸣式冲突",
    reusable_principles: ["冲突二元性", "做自己是最好定位", "低开高走"],
    risk_lessons: ["口号需产品性能支撑", "代言人风险需预案"],
    theory_tags: ["ye_maozhong"],
  },
  {
    id: "case-teayeah-failure",
    brand_name: "茶悦（化名）",
    category: "茶饮",
    city_context: "武汉",
    market_stage: "成长期",
    project_stage: "品牌升级",
    initial_problem: "国潮茶饮定位在茶颜霸王等强势品牌心智下逐渐模糊",
    resource_condition: "预算150万已有12家门店",
    competition_context: "茶颜长沙国风/霸王健康轻负担/喜茶灵感之茶",
    candidate_positions: ["武汉人自己的茶饮", "鲜果茶清爽不甜腻", "年轻人的第三空间"],
    final_position: "武汉人自己的茶饮——地域情感绑定",
    why_choose: "创始人认为武汉消费者会支持本地品牌",
    why_not_others: "其他两个方向无资源支撑且竞品已在跑",
    differentiation_design: "武汉方言包装黄鹤楼联名本地食材入茶",
    execution_actions: ["方言包装更换", "黄鹤楼联名限时3个月", "本地人喝本地茶话题", "老照片墙"],
    market_feedback: "联名期销量涨30%结束后回落80%本地人认证未能形成持续心智",
    result_summary: "失败：地域标签未与真实消费者心理冲突结合沦为一次性话题",
    success_or_failure: "failure",
    quality_tier: "bronze_case",
    mental_takeaway: "XX人自己的XX是自嗨型定位除非有外来品牌入侵的真实冲突",
    reusable_principles: ["地域标签必须有具体冲突或情感对立面支撑", "联名带来的流量不构建品牌资产", "定位需要每天被消费方式验证"],
    risk_lessons: ["高估地域自豪感在决策中的权重", "缺乏持续性场景绑定", "竞品降价联名跟随后差异消失"],
    theory_tags: ["ries", "trout"],
  },
];
