/**
 * 竞争空位学派 — 知识规则库
 *
 * 蒸馏来源：《定位》《与众不同》《大品牌大问题》《简单的力量》《终结营销混乱》《营销战》
 */
import type { TheoryRule } from "./types";

export const troutRules: TheoryRule[] = [
  {
    id: "trout-competitive-positioning",
    theory_source: "trout",
    name: "竞争性定位",
    principle: "定位不是关于品牌的自我表达，而是关于品牌在竞争结构中的位置",
    decision_question: "在竞争地图中，你的位置在哪里？",
    applicable_context: ["任何品类竞争场景", "战略评审", "新品牌进入"],
    key_variables: ["竞品心智地图", "空位识别", "差异化方向"],
    decision_rules: [
      "在谈定位之前，先画出竞争地图——谁占据了哪个心智位置？",
      "你的位置是由竞争对手的位置决定的，不是由你自己的愿望决定的",
      "如果你说不清竞争对手是谁、占据了什么位置，你的定位就是凭感觉的",
    ],
    anti_patterns: [
      "不分析竞品就谈定位",
      "只分析直接竞品而忽略替代性竞争",
      "认为定位是自己想做什么而不是竞争允许你做什么",
    ],
    output_implication: "候选方向必须明确回答：在竞争地图中它在什么位置？",
  },
  {
    id: "trout-differentiate-or-die",
    theory_source: "trout",
    name: "不差异化就死亡",
    principle: "在同质化市场中，差异化不是选择而是生存前提",
    decision_question: "如果消费者闭上眼睛想你的品牌，第一秒想到什么？",
    applicable_context: ["品类同质化严重", "头部品牌密集", "新进入者"],
    key_variables: ["差异化感知度", "差异化转述度", "差异化模仿难度"],
    decision_rules: [
      "在同质化的市场里，没有差异化的品牌等于不存在",
      "差异化必须存在于消费者感知中，而不是存在于产品参数中",
      "消费者说这家店和那家店差不多——这就是失败的信号",
      "差一个维度都比更好强——不同比好更重要",
    ],
    anti_patterns: [
      "把差异化理解为做得更好——消费者分不清谁更好",
      "做了差异但消费者感受不到",
      "做多个差异化等于没有差异化",
    ],
    output_implication: "候选方向必须有一个消费者可感知的差异化维度",
  },
  {
    id: "trout-war-defense",
    theory_source: "trout",
    name: "防御战原则",
    principle: "只有市场领导者才应该打防御战",
    decision_question: "这个品牌是市场领导者吗？它应该打防御战吗？",
    applicable_context: ["领导品牌", "品牌地位维护"],
    key_variables: ["市场份额领先度", "心智占有强度", "防御资源储备"],
    decision_rules: [
      "只有市场领导者才应该打防御战——其他人没有资格",
      "防御战的最佳策略是攻击自己——用新产品替代自己的旧产品",
      "领导者在防御时要随时准备封杀竞争对手的潜在攻击",
    ],
    anti_patterns: [
      "非领导品牌打防御战",
      "领导品牌在防御时选择不管而不是封杀",
      "领导品牌满足于现状不再自我攻击",
    ],
    output_implication: "非领导品牌不应选择防御型定位",
  },
  {
    id: "trout-war-offense",
    theory_source: "trout",
    name: "进攻战原则",
    principle: "进攻战的目标是领导者优势中的弱点",
    decision_question: "这个方向攻击的是领导者的真实弱点还是臆想的弱点？",
    applicable_context: ["挑战者品牌", "第二梯队品牌", "差异化切入"],
    key_variables: ["领导者弱点", "领导者可反击的空间", "攻击点的可持续性"],
    decision_rules: [
      "进攻战的目标是领导者优势中的弱点——不是任何弱点都可以",
      "如果领导者可以迅速弥补这个弱点，它就不是一个好的攻击点",
      "进攻者必须找到领导者优势中固有的弱点——这个弱点是领导者无法轻易改变的",
    ],
    anti_patterns: [
      "攻击领导者不重要的弱点",
      "攻击领导者可以迅速修复的弱点",
      "在多个方向上同时攻击",
    ],
    output_implication: "候选方向如果是挑战者定位，必须找到领导者优势中的固有弱点",
  },
  {
    id: "trout-war-flanking",
    theory_source: "trout",
    name: "侧翼战原则",
    principle: "侧翼战是在无争地带发起的突袭，是最适合新品牌的战术",
    decision_question: "这个方向是否进入了一个领导者无法或不愿意进入的市场？",
    applicable_context: ["新品牌", "资源有限", "寻找空位"],
    key_variables: ["无争地带的存在性", "侧翼突袭的突然性", "领导者的反应时间"],
    decision_rules: [
      "最好的侧翼战是进入一个完全无人竞争的地带",
      "侧翼战必须在战术上保持突然性",
      "侧翼成功后必须快速巩固成果，否则领导者会反击",
    ],
    anti_patterns: [
      "侧翼战变成了正面战",
      "侧翼成功后没有快速建立防御工事",
      "低估了领导者反击的速度和力度",
    ],
    output_implication: "新品牌最好的策略是侧翼战——找一个无争地带先站住脚",
  },
  {
    id: "trout-diff-attributes",
    theory_source: "trout",
    name: "从属性中找差异",
    principle: "差异化的核心来源是选择一个属性并独占它",
    decision_question: "这个品牌可以独占什么属性？",
    applicable_context: ["品类同质化", "寻找差异方向", "品牌定位"],
    key_variables: ["可占有的属性", "属性的消费者价值", "竞品对属性的占有度"],
    decision_rules: [
      "属性是差异化最直接的方式——最大、最新、最快、最贵、最便宜",
      "一个品牌只能占据一个属性——两个属性会互相削弱",
      "选择一个竞品没有占据的属性，然后持续强化它",
    ],
    anti_patterns: [
      "选择了一个竞品已经占据的属性",
      "试图同时占据两个属性",
      "选择了一个对消费者没有价值的属性",
    ],
    output_implication: "候选方向应围绕一个可独占的属性构建定位",
  },
  {
    id: "trout-first-association",
    theory_source: "trout",
    name: "第一联想法则",
    principle: "定位目标是需求出现时第一个被想起，不是被知道",
    decision_question: "消费者产生需求时会第一个想起你吗？",
    applicable_context: ["品类竞争激烈", "需建心智锚点", "多品牌同赛道"],
    key_variables: ["需求触发场景", "第一联想品牌", "关联强度"],
    decision_rules: [
      "需求产生时不会自然联想则定位未成功",
      "第一联想比知名度重要",
      "必须绑定具体需求场景",
    ],
    anti_patterns: [
      "高知名度不等于高心智占有率",
      "同时绑定多个不相关的联想",
      "联想是管理层想象的而非消费者认知的",
    ],
    output_implication: "第一联想方向做核心，其余都次要",
  },
  {
    id: "trout-simplicity",
    theory_source: "trout",
    name: "简单是终极武器",
    principle: "信息过载时代复杂信息无法进入心智，简单最有力量",
    decision_question: "能用最简单的话在3秒内说清楚吗？",
    applicable_context: ["品类信息复杂", "决策路径短", "传播资源有限"],
    key_variables: ["定位语长度复杂度", "复述准确度", "区分速度"],
    decision_rules: [
      "好的定位能用3秒说清3秒记住",
      "管理层需要一分钟解释的定位还不够简单",
      "去掉所有形容词只留名词和动词",
    ],
    anti_patterns: [
      "用抽象词汇显得有深度",
      "堆砌多个价值点",
      "书面语做定位语",
    ],
    output_implication: "定位语必须可被消费者3秒内复述",
  },
  {
    id: "trout-brand-trouble-signs",
    theory_source: "trout",
    name: "品牌危机的早期信号",
    principle: "大多数品牌危机在爆发前就有明确信号",
    decision_question: "这个品牌是否出现了品牌危机的早期信号？",
    applicable_context: ["品牌预警", "品牌诊断", "品牌复兴"],
    key_variables: ["销售下滑趋势", "品牌联想模糊", "竞品心智侵蚀"],
    decision_rules: [
      "品牌危机的第一个信号是销售下滑",
      "第二个信号是品牌联想开始模糊——消费者说不清你代表什么",
      "最危险的信号是内部认为品牌还好但外部已经变了",
    ],
    anti_patterns: [
      "用降价来应对品牌危机",
      "忽略品牌联想模糊的早期信号",
      "竞品心智侵蚀时反应太慢",
    ],
    output_implication: "品牌诊断时应检查是否有这些危机信号",
  },
  {
    id: "trout-simplicity-principle",
    theory_source: "trout",
    name: "简单原则",
    principle: "复杂的信息无法进入心智，简单是营销最强大的力量",
    decision_question: "这个定位的表述删掉一半字数后是否还成立？",
    applicable_context: ["定位表述优化", "传播素材", "品牌口号"],
    key_variables: ["信息量", "记忆成本", "转述难度"],
    decision_rules: [
      "一个好的定位应该能用一句话说清楚，能用3秒被记住",
      "如果定位需要三段话才能解释清楚，说明它还不够简单",
      "简单的标准是：一个初中生能听懂、能转述",
    ],
    anti_patterns: [
      "追求高级感而使用抽象词汇",
      "试图在定位语中包含所有优势",
      "把复杂的商业策略等同于复杂的定位表述",
    ],
    output_implication: "定位表述必须经过删半检验——删掉一半字数后还能说清吗？",
  },
  {
    id: "trout-repositioning",
    theory_source: "trout",
    name: "重新定位法则",
    principle: "改变消费者心智中已有的认知，比建立新认知更昂贵但有时必要",
    decision_question: "是需要重新定位竞品还是重新定位自己？",
    applicable_context: ["品牌老化", "竞品占位变化", "品类认知迁移"],
    key_variables: ["既有认知强度", "重新定位对象", "传播预算与耐心"],
    decision_rules: [
      "重新定位竞品：在消费者心智中移动竞争对手的位置",
      "重新定位自己：改变品牌已有的过时或负面联想",
      "重新定位需要长期、一致、简单的信息重复",
      "重新定位失败代价极高——不如开创新品类",
    ],
    anti_patterns: [
      "频繁改口号以为在重新定位",
      "重新定位语太复杂消费者记不住变化",
      "没有足够预算支撑重新定位就启动",
      "同时重新定位多个概念导致信息混乱",
    ],
    output_implication: "若选重新定位路径，须评估预算、时间与失败退路",
  },
  {
    id: "trout-mind-five-traps",
    theory_source: "trout",
    name: "心智五大陷阱",
    principle: "企业常因五种心智误区导致定位失败",
    decision_question: "这个方案是否落入心智五大陷阱之一？",
    applicable_context: ["战略评审", "定位诊断", "高层决策"],
    key_variables: ["组织傲慢", "复杂化倾向", "延伸冲动", "数据迷信", "更好陷阱"],
    decision_rules: [
      "陷阱一：更好陷阱——认为产品更好就能赢",
      "陷阱二：延伸陷阱——成功品牌向无关品类延伸",
      "陷阱三：复杂陷阱——用复杂信息展示专业",
      "陷阱四：数据陷阱——用调研数据代替心智现实",
      "陷阱五：共识陷阱——内部一致但消费者无感",
    ],
    anti_patterns: [
      "用市场份额短期波动证明定位正确",
      "把焦点小组喜欢等同于市场接受",
      "认为更多功能点等于更强定位",
      "忽视消费者第一联想只做品牌美誉度",
    ],
    output_implication: "方案须逐条对照五大陷阱并给出规避动作",
  },
  {
    id: "trout-big-brand-six-errors",
    theory_source: "trout",
    name: "大品牌六大错误",
    principle: "领导品牌常因六种典型错误丧失空位",
    decision_question: "作为领导品牌，这个方向是否触犯六大错误？",
    applicable_context: ["领导品牌", "品牌延伸", "多元化集团"],
    key_variables: ["品牌延伸范围", "子品牌管理", "创新节奏"],
    decision_rules: [
      "错误一：盲目延伸品牌名到无关品类",
      "错误二：满足所有人——失去鲜明立场",
      "错误三：模仿挑战者而稀释自身占位",
      "错误四：用复杂产品线掩盖定位模糊",
      "错误五：忽视侧翼攻击直到为时已晚",
      "错误六：把短期销量置于长期占位之上",
    ],
    anti_patterns: [
      "领导品牌看到小品牌成功就复制其定位",
      "用折扣维持份额损害品牌资产",
      "子品牌与主品牌争夺同一空位",
      "认为规模优势可以弥补定位模糊",
    ],
    output_implication: "领导品牌方案须标注是否触犯六大错误及防御措施",
  },
  {
    id: "trout-marketing-ten-principles",
    theory_source: "trout",
    name: "营销十大原则",
    principle: "有效营销遵循十条可检验原则，违反任一条都会削弱空位",
    decision_question: "这个定位符合营销十大原则中的几条？",
    applicable_context: ["全场景", "传播策略", "定位终审"],
    key_variables: ["简单性", "一致性", "差异化", "聚焦度", "可信度"],
    decision_rules: [
      "原则一：简单——一个词说清",
      "原则二：差异——与竞品可区分",
      "原则三：聚焦——放弃无关业务",
      "原则四：一致——多年重复同一信息",
      "原则五：可信——消费者能验证",
      "原则六：领先——争第一或对立面",
      "原则七：持久——不频繁改定位",
      "原则八：可见——在触点可被感知",
      "原则九：可战——有明确竞争对象",
      "原则十：可测——第一联想可检验",
    ],
    anti_patterns: [
      "十条原则满足三条以下仍强行推进",
      "以创意新颖代替原则检验",
      "每条原则都满足但彼此矛盾",
      "只满足内部原则不满足消费者感知",
    ],
    output_implication: "输出应含十大原则打分表，低于六条通过则降级",
  },
  {
    id: "trout-strategy-essence",
    theory_source: "trout",
    name: "战略的本质",
    principle: "战略不是目标清单，而是在竞争中占据一个可持续的心智位置",
    decision_question: "这是战略还是愿望？有没有明确的竞争位置和放弃项？",
    applicable_context: ["战略规划", "年度营销", "品牌架构"],
    key_variables: ["竞争位置", "放弃清单", "资源匹配"],
    decision_rules: [
      "战略必须回答：我们在竞争中代表什么、不代表什么",
      "没有放弃项的计划不是战略，是购物清单",
      "战略的成功标准是心智占位，不是短期营收",
      "战略应能指导所有战术决策——不符合战略的创意不做",
    ],
    anti_patterns: [
      "把营收目标当战略",
      "战略文档20页但说不出一个词",
      "战略与日常促销各自为政",
      "每年换战略导致占位无法积累",
    ],
    output_implication: "战略输出须含一词占位+竞争地图+放弃清单",
  },
  {
    id: "trout-duality-competition",
    theory_source: "trout",
    name: "二元法则（竞争视角）",
    principle: "从竞争视角看，成熟市场终将形成两个对立阵营，第三名被边缘化",
    decision_question: "能否成为二元阵营之一？否则如何侧翼或重新定位？",
    applicable_context: ["成熟品类", "市场份额分析", "挑战者策略"],
    key_variables: ["双寡头阵营", "第三梯队命运", "对立轴"],
    decision_rules: [
      "画出品类二元对立轴——如经典vs现代、高端vs平价",
      "成为轴上两极之一比做中间选项更有价值",
      "若无法成为二元之一，必须重新定义竞争轴",
      "二元格局下进攻战应强化对立而非更好",
    ],
    anti_patterns: [
      "在二元轴中间做「平衡者」",
      "同时讨好对立两极的消费者",
      "忽视品类正在形成的对立轴",
      "第三名仍按领导者逻辑投入",
    ],
    output_implication: "竞争地图须标注二元轴及品牌站位",
  },
  {
    id: "trout-long-term-law",
    theory_source: "trout",
    name: "长期法则",
    principle: "定位是长期资产，短期促销不能替代长期占位建设",
    decision_question: "这个方向是在建长期占位还是在换短期销量？",
    applicable_context: ["品牌建设", "促销评估", "KPI设计"],
    key_variables: ["占位一致性", "促销频率", "品牌资产指标"],
    decision_rules: [
      "长期占位靠同一信息的多年重复",
      "频繁促销会训练消费者等折扣，损害占位",
      "评估品牌应看第一联想变化，不只看当期销量",
      "短期牺牲占位换销量是借贷，迟早要还",
    ],
    anti_patterns: [
      "每季度换传播主题追热点",
      "用降价作为默认增长手段",
      "把电商销量等同于品牌成功",
      "占位建设无KPI只有销量KPI",
    ],
    output_implication: "方案须区分长期占位动作与短期销量动作",
  },
  {
    id: "trout-complexity-killer",
    theory_source: "trout",
    name: "复杂性是杀手",
    principle: "组织内部复杂性会杀死外部简单定位",
    decision_question: "内部产品/组织复杂度是否超出消费者能理解的简单定位？",
    applicable_context: ["产品线管理", "组织设计", "传播架构"],
    key_variables: ["SKU数量", "传播信息条数", "组织 silo"],
    decision_rules: [
      "产品线越复杂，定位越难简单",
      "每个事业部各说各话会杀死统一占位",
      "复杂性在内部合理，在消费者心智中是噪音",
      "简化组织是简化定位的前提",
    ],
    anti_patterns: [
      "100个SKU用一个定位语覆盖",
      "各渠道传播不同信息",
      "用子品牌解决复杂性但不做心智隔离",
      "认为消费者会像员工一样理解产品矩阵",
    ],
    output_implication: "定位前须评估组织/产品复杂度是否允许简单占位",
  },
  {
    id: "trout-marketing-chaos-root",
    theory_source: "trout",
    name: "营销混乱根源",
    principle: "营销混乱源于缺乏单一战略焦点，而非缺乏创意或预算",
    decision_question: "混乱是因为没焦点还是执行差？能否收束到一个词？",
    applicable_context: ["营销审计", "多 agency 协作", "品牌重塑"],
    key_variables: ["战略焦点数", "agency 口径", "内部优先级"],
    decision_rules: [
      "混乱的第一根源：同时追多个定位",
      "第二根源：把战术当战略——每个 campaign 一个主题",
      "第三根源：组织 KPI 与定位方向不一致",
      "终结混乱的方法：一个词、一个敌人、一个场景",
    ],
    anti_patterns: [
      "用更多预算掩盖战略缺失",
      "增加 agency 而不统一 brief",
      "老板个人偏好覆盖战略焦点",
      "认为混乱是创意行业的常态",
    ],
    output_implication: "诊断混乱须先找焦点缺失，再谈创意优化",
  },
  {
    id: "trout-diff-be-first",
    theory_source: "trout",
    name: "成为第一差异化",
    principle: "成为品类或细分第一本身是最强差异化",
    decision_question: "能否通过开创或命名细分成为第一？",
    applicable_context: ["新品类", "细分创新", "命名策略"],
    key_variables: ["细分可命名性", "第一窗口", "跟进者威胁"],
    decision_rules: [
      "第一的身份本身就是差异——消费者默认第一更好",
      "开创新细分并命名，比在大品类做更好更有效",
      "成为第一后应强化品类而非自夸品牌",
      "第一差异化需要快速建立防御",
    ],
    anti_patterns: [
      "在大品类做跟随者却宣称第一",
      "细分太小无法支撑第一叙事",
      "成为第一后不防御被侧翼超越",
      "把销量第一当心智第一",
    ],
    output_implication: "优先评估能否以「第一」作为核心差异点",
  },
  {
    id: "trout-diff-leadership",
    theory_source: "trout",
    name: "领导地位差异化",
    principle: "领导品牌应以权威和品类代表身份差异化，而非更好",
    decision_question: "作为领导者，是否在强调品类标准而非自夸？",
    applicable_context: ["市场领导者", "品类代表", "标准制定"],
    key_variables: ["品类话语权", "标准定义权", "防御投入"],
    decision_rules: [
      "领导者应说「我们是正宗/标准」而非「我们更好」",
      "领导地位差异化来自消费者默认的信任",
      "领导者应扩大品类蛋糕而非只抢份额",
      "用新品类攻击自己防止被侧翼颠覆",
    ],
    anti_patterns: [
      "领导者模仿挑战者定位",
      "领导者打价格战损害品类价值",
      "忽视小品牌侧翼直到份额流失",
      "领导品牌延伸稀释权威感",
    ],
    output_implication: "领导者方案应强化品类代表身份",
  },
  {
    id: "trout-diff-heritage",
    theory_source: "trout",
    name: "经典传承差异化",
    principle: "历史、传统、工艺传承是可防御的差异化，尤其在对快时尚品类",
    decision_question: "能否用真实传承故事占据「正宗/经典」空位？",
    applicable_context: ["老字号", "工艺品类", "文化品牌"],
    key_variables: ["历史真实性", "传承可验证性", "年轻消费者接受度"],
    decision_rules: [
      "传承差异化必须可验证——产地、工艺、年份",
      "正宗比更好更有防御性——难以复制",
      "传承需要现代化表达，不能只有怀旧",
      "挑战者的「新潮」往往与传承形成天然对立轴",
    ],
    anti_patterns: [
      "编造传承故事被消费者识破",
      "传承表达老气横秋无法触达年轻客群",
      "有传承但不传播等于没有",
      "传承与产品实际体验不一致",
    ],
    output_implication: "有真实传承 assets 时应评估经典空位机会",
  },
  {
    id: "trout-diff-market-specialty",
    theory_source: "trout",
    name: "市场专长差异化",
    principle: "聚焦特定市场、客群或区域做到最深，是有效的空位策略",
    decision_question: "能否在某一细分市场做到绝对第一？",
    applicable_context: ["区域品牌", "垂直品类", "B2B  niche"],
    key_variables: ["细分规模", "深耕深度", "扩张路径"],
    decision_rules: [
      "市场专长意味着在该细分比通用品牌更懂",
      "区域第一也是第一——不必急于全国化",
      "专长差异化需要放弃其他市场",
      "从专长市场扩张时须保持核心占位",
    ],
    anti_patterns: [
      "声称专长但产品线与通用品牌无异",
      "专长市场未站稳就全国扩张",
      "专长定位太窄无法盈利",
      "用专长做借口回避竞争",
    ],
    output_implication: "评估是否在可盈利的专长市场做第一",
  },
  {
    id: "trout-diff-making-method",
    theory_source: "trout",
    name: "制造方式差异化",
    principle: "独特的生产、工艺、原料或交付方式可以成为消费者可感知的差异",
    decision_question: "制造方式是否独特且可被消费者理解并传播？",
    applicable_context: ["制造业", "餐饮", "手工品类"],
    key_variables: ["工艺独特性", "可视化可能", "模仿难度"],
    decision_rules: [
      "制造方式差异必须能转化为消费者语言",
      "透明化展示（明厨亮灶、产地溯源）强化可信",
      "方式差异需要持续一致——一次曝光不够",
      "方式差异应与定位一词一致",
    ],
    anti_patterns: [
      "工艺独特但消费者感知不到",
      "制造方式差异无法规模化",
      "宣称方式差异但供应链无法支撑",
      "方式差异与价格带不匹配",
    ],
    output_implication: "有可展示工艺/方式时评估制造方式差异化路径",
  },
];
