/**
 * 冲突营销学派 — 知识规则库
 *
 * 蒸馏来源：《冲突营销听与说》《冲突策划：做自己》《创意就是权力》《营销的12个方法论》
 */
import type { TheoryRule } from "./types";

export const yeRules: TheoryRule[] = [
  {
    id: "ye-conflict-definition",
    theory_source: "ye_maozhong",
    name: "冲突是营销的第一原理",
    principle: "营销的本质不是满足需求，而是发现冲突、解决冲突、制造冲突",
    decision_question: "这个定位是否围绕一个真实的消费者冲突构建的？",
    applicable_context: ["任何营销场景", "品牌创立", "传播策略"],
    key_variables: ["冲突的真实性", "冲突的普遍性", "冲突与品牌的关联度"],
    decision_rules: [
      "没有冲突就没有记忆——消费者每天接触几千条信息，只有冲突能被记住",
      "需求的本质是冲突——消费者想要和能够之间的差距",
      "营销的任务不是满足需求而是解决冲突",
    ],
    anti_patterns: [
      "编造一个消费者不感受的冲突",
      "忽略真实冲突而讲一个完美的品牌故事",
      "解决了冲突但消费者不认为这是个问题",
    ],
    output_implication: "没有清晰冲突结构的方向在冲突营销视角下天然处于劣势",
  },
  {
    id: "ye-conflict-scene-binding",
    theory_source: "ye_maozhong",
    name: "场景是冲突的触发器",
    principle: "冲突需要一个具体的场景来激活——没有场景的冲突消费者无法关联自身",
    decision_question: "这个冲突在什么场景下被触发？",
    applicable_context: ["品牌起步期", "传播预算有限", "品类抽象"],
    key_variables: ["场景的真实性", "场景的高频度", "场景与冲突的关联度"],
    decision_rules: [
      "冲突不能抽象存在——消费者需要在一个具体场景中感受到它",
      "场景越具体越好——周末家庭聚餐比家人团聚好一万倍",
      "高频场景比低频场景更有价值",
    ],
    anti_patterns: [
      "冲突口号想到了但不知道在什么场景下用",
      "场景是编造的不存在于消费者的真实生活中",
      "场景一年才发生一次无法支撑品牌记忆",
    ],
    output_implication: "每个定位必须有明确的场景触发器",
  },
  {
    id: "ye-conflict-opposite",
    theory_source: "ye_maozhong",
    name: "制造对立面",
    principle: "最有效的冲突结构是制造旧选择vs新选择的对立面",
    decision_question: "这个定位是否创造了一个清晰的对立结构？",
    applicable_context: ["品牌重塑", "挑战者品牌", "差异化定位"],
    key_variables: ["旧选择的痛点", "新选择的解决方案", "对立面的清晰度"],
    decision_rules: [
      "以前你得忍受X，现在你可以享受Y——这是最有效的冲突表达结构",
      "对立面越具象越好——不要对抽象的敌人开战",
      "让消费者觉得以前我一直在将就——这是最好的心理暗示",
    ],
    anti_patterns: [
      "制造了一个消费者并不觉得有问题的对立面",
      "对立面太抽象消费者听不懂",
      "只说了不要旧选择但没说明白新选择是什么",
    ],
    output_implication: "优先选择有明确对立结构的候选方向",
  },
  {
    id: "ye-method-market-insight",
    theory_source: "ye_maozhong",
    name: "洞察是营销的起点",
    principle: "没有洞察的营销等于在黑暗中开枪",
    decision_question: "这个定位背后的消费者洞察是什么？",
    applicable_context: ["定位策略制定", "消费者研究", "市场进入"],
    key_variables: ["洞察的深度", "洞察的真实性", "洞察的可行动性"],
    decision_rules: [
      "洞察必须先于策略——没有洞察就没有方向感",
      "消费者洞察不是数据堆砌，而是找到消费者自己都没说出来的真相",
      "女性都爱美不是洞察——女性怕老怕丑怕被比较才是洞察",
    ],
    anti_patterns: [
      "用数据代替洞察",
      "用常识代替洞察",
      "根本不做洞察就直接做定位",
    ],
    output_implication: "每个候选方向必须有对应的消费者洞察支撑",
  },
  {
    id: "ye-method-repetition",
    theory_source: "ye_maozhong",
    name: "重复是记忆的母亲",
    principle: "一次性的沟通等于没有沟通，持续重复才能进入心智",
    decision_question: "这个定位是否经得起持续重复？",
    applicable_context: ["传播策略", "品牌建设", "定位沉淀"],
    key_variables: ["重复的可持续性", "重复的维度", "消费者的审美疲劳风险"],
    decision_rules: [
      "一次性的大广告不如持续的重复小信息",
      "定位表达要有足够的简洁度来支撑持续重复",
      "一个不能持续重复的定位等于没有定位",
    ],
    anti_patterns: [
      "定位语太复杂无法在广告中持续重复",
      "每个季度的传播主题完全不同",
      "品牌方自己先厌倦了自己的定位而频繁更换",
    ],
    output_implication: "定位语必须简洁到可以持续重复一年以上",
  },
  {
    id: "ye-method-verbal-spread",
    theory_source: "ye_maozhong",
    name: "口语是最高级的传播语言",
    principle: "消费者不会用书面语转述品牌",
    decision_question: "消费者会怎么用他自己的话转述这个定位？",
    applicable_context: ["定位语设计", "品牌口号", "传播内容"],
    key_variables: ["口语化程度", "转述准确度", "转述的主动性"],
    decision_rules: [
      "定位语在文档里再精彩也不如在消费者嘴里说出来精彩",
      "检查标准：去楼下小店店主能不能说给邻居听？",
      "让消费者愿意主动转述的关键：有用、有面子",
    ],
    anti_patterns: [
      "定位语是书面语",
      "定位语太长导致消费者转述时自动省略",
      "定位语太复杂消费者转述时会走样",
    ],
    output_implication: "定位语必须经过口语转述测试",
  },
  {
    id: "ye-method-trigger-word",
    theory_source: "ye_maozhong",
    name: "触发词法则",
    principle: "某些词语天然具有更高的记忆和传播效率",
    decision_question: "这个定位中有没有触发词？",
    applicable_context: ["品牌命名", "定位语撰写", "传播策略"],
    key_variables: ["触发词的记忆度", "触发词的传播力", "触发词的独特性"],
    decision_rules: [
      "某些词天生就比别的词更容易被记住和传播",
      "在定位中嵌入一个触发词可以显著降低传播成本",
      "一个好的触发词本身就值一千万广告费",
    ],
    anti_patterns: [
      "定位语中充斥着消费者每天听到的麻木词语",
      "用了有趣的词但和品牌定位没有关系",
      "触发词太突兀让消费者觉得莫名其妙",
    ],
    output_implication: "定位语中应嵌入至少一个触发词",
  },
  {
    id: "ye-method-selling-point",
    theory_source: "ye_maozhong",
    name: "购买理由比品牌故事更重要",
    principle: "消费者不关心品牌的故事，他们关心为什么要选你",
    decision_question: "这个定位是否给了消费者一个明确的购买理由？",
    applicable_context: ["转化率提升", "销售话术", "定位验证"],
    key_variables: ["购买理由的强度", "购买理由的独特性", "购买理由的真实性"],
    decision_rules: [
      "消费者不关心品牌故事，他们只关心我为什么要选你",
      "好的定位本身就包含一个强有力的购买理由",
      "购买理由必须具体——越抽象越没有说服力",
    ],
    anti_patterns: [
      "用品牌故事替代购买理由",
      "购买理由太抽象",
      "购买理由不具备排他性",
    ],
    output_implication: "每个候选方向必须包含一个清晰的、排他的购买理由",
  },
  {
    id: "ye-ad-no-big-words",
    theory_source: "ye_maozhong",
    name: "不说大话",
    principle: "说人话比说大话难一万倍",
    decision_question: "这个定位是否在说大话？",
    applicable_context: ["定位语撰写", "品牌口号", "传播内容"],
    key_variables: ["语言的具体度", "语言的真诚度", "语言的差异化"],
    decision_rules: [
      "广告中最浪费钱的就是消费者看不懂的大话",
      "引领生活方、重新定义XX、赋能——这些词消费者根本听不懂",
      "越是大品牌越说小话",
    ],
    anti_patterns: [
      "用宏大词汇包装普通的商业逻辑",
      "定位语在行业大会上很有面子但消费者听不懂",
      "竞品都在说大话时以为自己也应该说大话",
    ],
    output_implication: "定位语中不应出现任何消费者听不懂的抽象词汇",
  },
  {
    id: "ye-plan-execution-first",
    theory_source: "ye_maozhong",
    name: "执行比策略重要",
    principle: "中国市场上90%的营销失败不是策略错了，是执行不到位",
    decision_question: "这个定位在中国市场的执行落地有把握吗？",
    applicable_context: ["执行评估", "资源匹配", "落地可行性"],
    key_variables: ["执行能力", "可交付程度", "资源匹配度"],
    decision_rules: [
      "好的策略遇到差的执行等于零效果",
      "一个可执行的一般策略远胜于一个不可执行的完美策略",
      "在执行力有限的情况下，宁可选简单但能执行到位的定位",
    ],
    anti_patterns: [
      "策略很精彩但团队做不出来",
      "低估了中国市场执行的复杂性",
      "认为创意好就够了",
    ],
    output_implication: "不可执行的定位在冲突营销视角下直接降级",
  },
  {
    id: "ye-plan-local-reality",
    theory_source: "ye_maozhong",
    name: "中国市场的特殊性",
    principle: "中国市场与国际市场有本质差异",
    decision_question: "这个定位是否考虑了中国市场现实？",
    applicable_context: ["中国品牌定位", "下沉市场", "区域品牌"],
    key_variables: ["中国市场特征", "消费者行为差异", "基础设施与渠道差异"],
    decision_rules: [
      "中国消费者更感性、更冲动、品牌忠诚度更低",
      "中国市场的渠道比品牌更有话语权",
      "中国消费者对价格更敏感",
    ],
    anti_patterns: [
      "照搬西方品牌定位理论忽略中国市场特征",
      "认为中国消费者和西方消费者一样理性",
      "忽略了中国各区域的市场差异",
    ],
    output_implication: "定位策略必须适配中国市场的具体条件",
  },
  {
    id: "ye-campaign-small-test",
    theory_source: "ye_maozhong",
    name: "小范围试错",
    principle: "不要一上来就大张旗鼓——先用最小成本验证定位的有效性",
    decision_question: "这个定位能否用最小的成本先验证？",
    applicable_context: ["新品牌", "预算有限", "不确定的定位"],
    key_variables: ["验证成本", "验证周期", "验证指标"],
    decision_rules: [
      "大干快上是最大的浪费——在验证之前就投入大预算",
      "先用一家店、一个社区、一个渠道验证定位效果",
      "验证至少需要30天——首周的新鲜感不能代表长期有效",
    ],
    anti_patterns: [
      "一上来就大规模铺开",
      "验证时间太短",
      "验证指标太多太复杂",
    ],
    output_implication: "所有定位都应设计30天最小验证方案",
  },
  {
    id: "ye-campaign-opportunity",
    theory_source: "ye_maozhong",
    name: "借势比造势更重要",
    principle: "借消费者的既有认知之势，比凭空创造认知容易一万倍",
    decision_question: "这个定位借了消费者的什么既有认知之势？",
    applicable_context: ["品牌定位", "传播策略", "市场教育"],
    key_variables: ["可借之势的类型", "之势的强度", "之势的匹配度"],
    decision_rules: [
      "借势比造势更重要——消费者已经接受的概念不需要你重新教育",
      "可借之势：已有的品类认知、文化共识、社会热点",
      "最好的定位是让消费者觉得本来就应该这样",
    ],
    anti_patterns: [
      "逆着消费者的既有认知做定位",
      "明明有势可借却偏要造势",
      "借势但借错了势",
    ],
    output_implication: "候选方向应优先利用消费者已有的认知趋势",
  },
  {
    id: "ye-conflict-three-layers",
    theory_source: "ye_maozhong",
    name: "冲突三层次",
    principle: "有效冲突存在于物理、心理、文化三个层次，越深越难被模仿",
    decision_question: "这个冲突打在哪个层次？能否向下扎深？",
    applicable_context: ["冲突挖掘", "洞察深化", "差异化设计"],
    key_variables: ["物理层冲突", "心理层冲突", "文化层冲突"],
    decision_rules: [
      "物理层：产品功能、价格、便利性的直接冲突",
      "心理层：身份认同、面子、焦虑、归属的冲突",
      "文化层：价值观、代际、地域、生活方式的冲突",
      "越深层的冲突记忆越持久、模仿越难",
    ],
    anti_patterns: [
      "只在物理层打价格战",
      "心理层冲突编造消费者无感",
      "文化层冲突与品牌能力不匹配",
      "三层冲突互相矛盾无法统一表达",
    ],
    output_implication: "优先选择可扎到心理层及以上的冲突结构",
  },
  {
    id: "ye-conflict-duality",
    theory_source: "ye_maozhong",
    name: "冲突二元性",
    principle: "强冲突往往呈现二元对立——旧我vs新我、将就vs讲究、随大流vs做自己",
    decision_question: "冲突是否呈现清晰的二元对立？消费者站在哪一边？",
    applicable_context: ["口号创作", "品牌人格", "传播叙事"],
    key_variables: ["二元轴", "消费者自我认同", "对立强度"],
    decision_rules: [
      "二元冲突让消费者必须选边——选边就有记忆",
      "有效的二元：男人vs自己、传统vs年轻、便宜vs有面子",
      "品牌应站在消费者想成为的那一边",
      "二元表达要口语化、可转述",
    ],
    anti_patterns: [
      "二元对立太极端引发反感",
      "二元轴与消费者无关",
      "只树立敌人不给出路",
      "二元结构在传播中时被时无",
    ],
    output_implication: "冲突表达须含清晰二元轴及品牌站位",
  },
  {
    id: "ye-creative-rooted-insight",
    theory_source: "ye_maozhong",
    name: "创意根植洞察",
    principle: "没有洞察支撑的创意是空中楼阁，有洞察的创意自带传播力",
    decision_question: "这个创意的洞察是什么？没有洞察请重做",
    applicable_context: ["广告创意", "Campaign 评审", "定位语创作"],
    key_variables: ["洞察深度", "创意与洞察绑定度", "可验证性"],
    decision_rules: [
      "好创意是洞察的意外呈现——消费者说「对，我就是这样」",
      "洞察→冲突→创意，顺序不能颠倒",
      "创意测试标准：消费者能否在3秒内get到洞察",
      "一个洞察可以支撑多年创意变体",
    ],
    anti_patterns: [
      "为创意而创意无洞察锚点",
      "洞察是团队内部共识消费者无感",
      "每个 campaign 换洞察导致品牌无积累",
      "用热点嫁接代替洞察驱动",
    ],
    output_implication: "每个创意产出须标注对应洞察及冲突结构",
  },
  {
    id: "ye-ad-brand-asset",
    theory_source: "ye_maozhong",
    name: "广告是品牌资产投资",
    principle: "广告不是费用而是投资——每次传播应积累可复用的品牌资产",
    decision_question: "这次传播是在消耗预算还是在积累资产？",
    applicable_context: ["媒介策略", "Campaign 规划", "预算分配"],
    key_variables: ["资产沉淀", "重复一致性", "资产可识别度"],
    decision_rules: [
      "品牌资产包括：固定表达、视觉锤、声音识别、冲突口号",
      "一次性 campaign 不积累资产等于烧钱",
      "评估广告看五年后消费者还记得什么",
      "资产投资需要克制——元素越少越能积累",
    ],
    anti_patterns: [
      "每波广告换一套视觉和口号",
      "追热点牺牲品牌资产一致性",
      "把短期转化等同于广告成功",
      "资产元素过多消费者记不住任何一个",
    ],
    output_implication: "传播方案须列出要积累的资产元素及重复计划",
  },
  {
    id: "ye-creative-is-power",
    theory_source: "ye_maozhong",
    name: "创意就是权力",
    principle: "在信息过载时代，能击穿噪音的创意就是品牌权力",
    decision_question: "这个创意有没有权力感——让人停、看、记、传？",
    applicable_context: ["创意终审", "传播突破", "竞争对抗"],
    key_variables: ["停止力", "记忆度", "传播欲", "竞争区隔"],
    decision_rules: [
      "没权力的创意是装饰——消费者滑过去",
      "权力来自冲突的尖锐度和表达的独特性",
      "创意权力需要与定位一致——权力不能偏离占位",
      "小预算更依赖创意权力而非媒介权力",
    ],
    anti_patterns: [
      "美观但无冲突的创意",
      "有权力但与定位无关",
      "模仿竞品创意结构失去区隔",
      "权力靠恶俗博眼球损害品牌",
    ],
    output_implication: "创意须通过停看记传四格检验",
  },
  {
    id: "ye-common-sense-test",
    theory_source: "ye_maozhong",
    name: "用常识判断",
    principle: "复杂模型不如常识——回到街头问普通人是否理解",
    decision_question: "一个普通消费者会用常识理解并接受这个定位吗？",
    applicable_context: ["策略终审", "内部评审", "定位简化"],
    key_variables: ["常识可理解性", "街头测试结果", "反常识风险"],
    decision_rules: [
      "策略会上通过不等于市场通过",
      "常识测试：问出租车司机、问便利店店员",
      "违背常识的定位需要极强证据支撑",
      "常识往往指向真正的冲突",
    ],
    anti_patterns: [
      "用行业术语自嗨",
      "只问专家不问普通人",
      "把反常识当创意",
      "常识测试走过场",
    ],
    output_implication: "终审须含常识/街头测试结果",
  },
  {
    id: "ye-planning-system",
    theory_source: "ye_maozhong",
    name: "策划是系统工程",
    principle: "定位不是一句口号，而是洞察、产品、渠道、传播、执行的系统对齐",
    decision_question: "各环节是否围绕同一冲突对齐？哪里是系统短板？",
    applicable_context: ["全案策划", "落地评审", "组织协作"],
    key_variables: ["系统一致性", "短板环节", "协同机制"],
    decision_rules: [
      "策划=洞察×冲突×创意×产品×渠道×传播",
      "任一环节与冲突不对齐则系统失效",
      "先找系统最短板再优化最长板",
      "策划文档须可执行到具体触点",
    ],
    anti_patterns: [
      "传播与产品体验两张皮",
      "渠道推的产品与定位无关",
      "只有口号没有触点设计",
      "各部门 KPI 与冲突方向冲突",
    ],
    output_implication: "输出须含系统对齐图及短板 remedial 动作",
  },
  {
    id: "ye-listen-first",
    theory_source: "ye_maozhong",
    name: "先听后说",
    principle: "说之前必须先听——听消费者、听市场、听竞品在消费者心中的声音",
    decision_question: "我们听了什么？说（定位）是否基于听到的？",
    applicable_context: ["调研阶段", "定位启动", "策略复盘"],
    key_variables: ["倾听深度", "原话记录", "听的渠道多样性"],
    decision_rules: [
      "听不是问卷——是进店、进店、听原话",
      "消费者怎么骂竞品、怎么将就现有选择，都是金矿",
      "先听后说顺序不可逆",
      "听到的冲突比想出来的冲突更真实",
    ],
    anti_patterns: [
      "没调研直接出定位",
      "只听经销商不听终端消费者",
      "用二手报告代替亲耳听",
      "听了但策略与听到的不一致",
    ],
    output_implication: "定位启动须附倾听记录及提炼的冲突原话",
  },
  {
    id: "ye-be-yourself-positioning",
    theory_source: "ye_maozhong",
    name: "做自己是最好定位",
    principle: "强行模仿他人定位必败，基于自身真实能力长出的定位最可持续",
    decision_question: "这个定位是做自己还是做别人？",
    applicable_context: ["品牌创立", "定位选型", "能力匹配"],
    key_variables: ["真实能力", "创始人基因", "可持续交付"],
    decision_rules: [
      "定位必须来自你能长期做到的事",
      "模仿竞品定位短期有效长期崩塌",
      "做自己不是不做差异——是用自己的方式做差异",
      "消费者能感知真假——装出来的定位会露馅",
    ],
    anti_patterns: [
      "竞品做什么我做什么",
      "定位超出组织能力",
      "创始人不信自己的定位",
      "为了差异化而虚假承诺",
    ],
    output_implication: "定位须与组织能力 authenticity 检验通过",
  },
  {
    id: "ye-china-innovation",
    theory_source: "ye_maozhong",
    name: "中国式创新",
    principle: "中国市场的创新往往是微创新+强传播+快迭代，而非纯技术突破",
    decision_question: "创新是否适配中国市场的节奏和消费者的感性决策？",
    applicable_context: ["新品类", "产品迭代", "传播创新"],
    key_variables: ["微创新点", "传播放大", "迭代速度"],
    decision_rules: [
      "中国式创新：小改进+大传播+快复制",
      "消费者为感知到的创新买单，不为实验室参数买单",
      "创新需要热点和冲突包装才能进入心智",
      "快速迭代比一次完美更重要",
    ],
    anti_patterns: [
      "技术领先但消费者无感",
      "创新无传播等于没创新",
      "照搬硅谷创新节奏在中国市场水土不服",
      "创新点太多消费者记不住",
    ],
    output_implication: "创新方案须含传播放大和迭代节奏",
  },
  {
    id: "ye-create-hotspot",
    theory_source: "ye_maozhong",
    name: "制造热点",
    principle: "没有热点就要制造热点——冲突本身可以是热点",
    decision_question: "这个定位能否制造或嫁接热点？",
    applicable_context: ["传播启动", "事件营销", "社交传播"],
    key_variables: ["热点关联度", "制造可能性", "负面风险"],
    decision_rules: [
      "热点=冲突的公共化表达",
      "可制造热点：争议、对比、挑战、仪式",
      "热点须与定位一致——蹭无关热点无效",
      "制造热点需要勇气和资源兜底",
    ],
    anti_patterns: [
      "蹭热点与品牌无关",
      "制造热点引发舆论反噬",
      "只有热点没有定位沉淀",
      "热点一过品牌归零",
    ],
    output_implication: "传播须含热点策略及与定位的绑定方式",
  },
  {
    id: "ye-low-open-high-walk",
    theory_source: "ye_maozhong",
    name: "低开高走",
    principle: "传播节奏应低开高走——先小范围验证冲突有效再放大投入",
    decision_question: "是否遵循低开高走？有没有一上来就all in？",
    applicable_context: ["预算分配", "上市节奏", "Campaign 规划"],
    key_variables: ["验证阶段", "放大阈值", "止损机制"],
    decision_rules: [
      "低开：小范围测试冲突是否引发共鸣",
      "高走：验证成功后集中资源放大",
      "低开不是低质——是低预算高精准",
      "高走需要预设放大触发指标",
    ],
    anti_patterns: [
      "未验证就全国投放",
      "低开阶段数据解读错误",
      "验证失败仍强行高走",
      "低开太久错过窗口",
    ],
    output_implication: "传播计划须分低开/高走两阶段及触发条件",
  },
  {
    id: "ye-different-not-better",
    theory_source: "ye_maozhong",
    name: "不同比更好更重要",
    principle: "消费者记不住更好，但能记住不同——冲突来自差异而非优劣",
    decision_question: "这个定位是在说不同还是在说更好？",
    applicable_context: ["定位语", "竞争策略", "传播对比"],
    key_variables: ["差异维度", "更好陷阱", "可感知度"],
    decision_rules: [
      "更好没有标准——不同有标准",
      "冲突结构应建立在差异轴上而非优劣轴上",
      "说更好会陷入比较——说不同会建立新类别",
      "不同必须可感知、可转述",
    ],
    anti_patterns: [
      "定位语含最好、第一、领先但无证据",
      "不同点太小消费者感知不到",
      "假不同——本质仍是更好",
      "不同与产品实际不符",
    ],
    output_implication: "定位语禁用更好逻辑，改用不同逻辑表达",
  },
];
