export const DEMO_EVIDENCE = [
  {
    id: "d1",
    source: "大众点评",
    claim: "环境适合朋友聚餐，拍照好看",
    sentiment: "positive" as const,
    theme: "environment",
  },
  {
    id: "d2",
    source: "大众点评",
    claim: "菜味道比较正宗",
    sentiment: "positive" as const,
    theme: "product",
  },
  {
    id: "d3",
    source: "大众点评",
    claim: "周末等位太久，上菜慢",
    sentiment: "negative" as const,
    theme: "wait",
  },
  {
    id: "d4",
    source: "大众点评",
    claim: "服务跟不上高峰",
    sentiment: "negative" as const,
    theme: "wait",
  },
  {
    id: "d5",
    source: "小红书",
    claim: "适合聚会，但要做好久等的心理准备",
    sentiment: "neutral" as const,
    theme: "wait",
  },
  {
    id: "d6",
    source: "大众点评",
    claim: "人均偏贵，性价比一般",
    sentiment: "negative" as const,
    theme: "price",
  },
  {
    id: "d7",
    source: "小红书",
    claim: "环境干净，氛围不错，适合约会",
    sentiment: "positive" as const,
    theme: "environment",
  },
];
