/**
 * M-BIZ 商业模式案例库
 */
import type { CaseStudy } from "../types";

const C1: CaseStudy = { id: "BIZ-CASE-001", title: "麦当劳：地产才是真正的商业模式", category: "餐饮", industry: "快餐", basics: { city: "全球" }, timeline: [{ date: "1955", event: "发现地产价值", action: "以加盟费做地产杠杆", result: "利润远超卖汉堡" }], outcome: { status: "success", duration: "1955-至今" }, lessons: ["真正利润来自地产升值+租金，不是汉堡", "商业模式的核心是利润结构设计"], applicableScenarios: ["商业模式设计", "利润结构"], source: "McDonald's: Behind The Arches", confidence: 0.95 };
const C2: CaseStudy = { id: "BIZ-CASE-002", title: "达美乐披萨：从卖披萨转型为科技公司", category: "餐饮", industry: "快餐", basics: { city: "全球" }, timeline: [{ date: "2009", event: "转型", action: "数字化+披萨追踪", result: "股价翻30倍" }], outcome: { status: "success", duration: "2009-至今" }, lessons: ["科技体验可以成为餐饮壁垒", "商业模式创新比产品创新更容易规模化"], applicableScenarios: ["数字化转型", "商业模式创新"], source: "Domino's财报", confidence: 0.9 };
const C3: CaseStudy = { id: "BIZ-CASE-003", title: "蜜雪冰城：供应链利润模型", category: "餐饮", industry: "茶饮", basics: { city: "中国" }, timeline: [{ date: "2010s", event: "自建供应链", action: "自建原料工厂", result: "成本优势" }], outcome: { status: "success", duration: "1997-至今" }, lessons: ["利润在供应链端不在门店端", "极致性价比靠极致供应链"], applicableScenarios: ["供应链模式", "利润结构"], source: "蜜雪冰城招股书", confidence: 0.9 };
const C4: CaseStudy = { id: "BIZ-CASE-004", title: "Costco会员模式：利润来自会员费", category: "零售", industry: "零售", basics: { city: "全球" }, timeline: [{ date: "1983", event: "创立", action: "会员制仓储", result: "商品毛利率不超14%" }], outcome: { status: "success", duration: "1983-至今" }, lessons: ["商品不赚钱+会员费=纯利", "倒逼必须把会员体验做到极致"], applicableScenarios: ["会员模式", "利润结构设计"], source: "Costco年报", confidence: 0.9 };
const C5: CaseStudy = { id: "BIZ-CASE-005", title: "海底捞：服务溢价的单位经济验证", category: "餐饮", industry: "火锅", basics: { city: "中国" }, timeline: [{ date: "1994", event: "创立", action: "服务差异化", result: "高于同行客单价" }], outcome: { status: "success", duration: "1994-至今" }, lessons: ["服务溢价可以成立但需要组织能力", "高翻台率+高客单价=利润模型"], applicableScenarios: ["服务溢价", "差异化定价"], source: "海底捞招股书", confidence: 0.85 };
const C6: CaseStudy = { id: "BIZ-CASE-006", title: "ofo：规模经济的致命幻觉", category: "出行", industry: "共享经济", basics: { city: "中国" }, timeline: [{ date: "2014", event: "创立", action: "烧钱扩张", result: "2018破产" }], outcome: { status: "failure", duration: "2014-2018" }, lessons: ["单位经济不成立的规模增长=放大亏损", "把融资当收入=融资停公司停"], applicableScenarios: ["单位经济", "规模陷阱"], source: "ofo失败复盘", confidence: 0.9 };
const C7: CaseStudy = { id: "BIZ-CASE-007", title: "美团：高频带低频的飞轮", category: "互联网", industry: "本地生活", basics: { city: "中国" }, timeline: [{ date: "2010", event: "创立", action: "团购起步", result: "高频流量" }], outcome: { status: "success", duration: "2010-至今" }, lessons: ["外卖亏钱但带流量，酒旅赚钱但低频", "交叉销售改变单一业务UE"], applicableScenarios: ["飞轮效应", "交叉销售"], source: "美团招股书", confidence: 0.85 };
const C8: CaseStudy = { id: "BIZ-CASE-008", title: "戴尔：零库存的现金周期奇迹", category: "科技", industry: "硬件", basics: { city: "全球" }, timeline: [{ date: "1984", event: "直销模式", action: "先收款后生产", result: "现金周期为负" }], outcome: { status: "success", duration: "1984-至今" }, lessons: ["现金周期为负是最强的财务武器", "供应链效率可以是核心壁垒"], applicableScenarios: ["现金流管理", "供应链效率"], source: "Dell模式分析", confidence: 0.85 };
const C9: CaseStudy = { id: "BIZ-CASE-009", title: "俏江南：对赌协议的致命后果", category: "餐饮", industry: "餐饮", basics: { city: "中国" }, timeline: [{ date: "2008", event: "签对赌", action: "对赌上市", result: "张兰失去公司" }], outcome: { status: "failure", duration: "2008-2014" }, lessons: ["对赌协议是餐饮企业最危险的条款", "不要签无法控制的对赌条件"], applicableScenarios: ["对赌协议", "融资风险"], source: "俏江南融资复盘", confidence: 0.9 };
const C10: CaseStudy = { id: "BIZ-CASE-010", title: "瑞幸造假前：烧钱换增长的崩塌", category: "餐饮", industry: "咖啡", basics: { city: "中国" }, timeline: [{ date: "2017", event: "烧钱扩张", action: "疯狂补贴", result: "2020造假曝光退市" }], outcome: { status: "failure", duration: "2017-2020" }, lessons: ["补贴驱动的需求不是真实需求", "没有盈利路径的商业模式是定时炸弹"], applicableScenarios: ["烧钱模式", "单位经济"], source: "瑞幸事件复盘", confidence: 0.85 };

export const BUSINESS_MODEL_CASES: CaseStudy[] = [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10];
