/**
 * 叶茂中冲突营销理论 — 知识规则库
 * 
 * 蒸馏来源：冲突、营销的12个方法论、广告人手记、创意就是权力、转身看策划
 */
import type { TheoryRule } from "./knowledge-loader";

export const yeRules: TheoryRule[] = [
  {
    id: "ye-conflict-definition",
    theory_source: "ye_maozhong",
    name: "冲突是营销的第一原理",
    principle: "营销的本质不是满足需求，而是发现冲突、解决冲突、制造冲突",
    decision_question: "这个定位是否围绕一个真实的消费者冲突构建的？",
    applicable_context: ["任何营销场景"],
    key_variables: ["冲突的真实性", "冲突的普遍性", "冲突与品牌的关联度"],
    decision_rules: [
      "没有冲突就没有记忆——消费者每天接触几千条信息，只有冲突能被记住",
      "需求的本质是冲突——消费者想要和能够之间的差距",
      "营销的任务不是满足需求而是解决冲突",
    ],
    anti_patterns: [
      "编造一个消费者不感受的冲突",
      "忽略真实冲突而讲一个完美的品牌故事",
      "解决了冲突但消费者不认为这是个问题",
    ],
    output_implication: "没有清晰冲突结构的方向在叶茂中视角下天然处于劣势",
  },
  {
    id: "ye-conflict-scene-binding",
    theory_source: "ye_maozhong",
    name: "场景是冲突的触发器",
    principle: "冲突需要一个具体的场景来激活——没有场景的冲突消费者无法关联自身",
    decision_question: "这个冲突在什么场景下被触发？",
    applicable_context: ["品牌起步期", "传播预算有限", "品类抽象"],
    key_variables: ["场景的真实性", "场景的高频度", "场景与冲突的关联度"],
    decision_rules: [
      "冲突不能抽象存在——消费者需要在一个具体场景中感受到它",
      "场景越具体越好——周末家庭聚餐比家人团聚好一万倍",
      "高频场景比低频场景更有价值",
    ],
    anti_patterns: [
      "冲突口号想到了但不知道在什么场景下用",
      "场景是编造的不存在于消费者的真实生活中",
      "场景一年才发生一次无法支撑品牌记忆",
    ],
    output_implication: "每个定位必须有明确的场景触发器",
  },
  {
    id: "ye-conflict-opposite",
    theory_source: "ye_maozhong",
    name: "制造对立面",
    principle: "最有效的冲突结构是制造旧选择vs新选择的对立面",
    decision_question: "这个定位是否创造了一个清晰的对立结构？",
    applicable_context: ["品牌重塑", "挑战者品牌", "差异化定位"],
    key_variables: ["旧选择的痛点", "新选择的解决方案", "对立面的清晰度"],
    decision_rules: [
      "以前你得忍受X，现在你可以享受Y——这是最有效的冲突表达结构",
      "对立面越具象越好——不要对抽象的敌人开战",
      "让消费者觉得以前我一直在将就——这是最好的心理暗示",
    ],
    anti_patterns: [
      "制造了一个消费者并不觉得有问题的对立面",
      "对立面太抽象消费者听不懂",
      "只说了不要旧选择但没说明白新选择是什么",
    ],
    output_implication: "优先选择有明确对立结构的候选方向",
  },
  {
    id: "ye-method-market-insight",
    theory_source: "ye_maozhong",
    name: "洞察是营销的起点",
    principle: "没有洞察的营销等于在黑暗中开枪",
    decision_question: "这个定位背后的消费者洞察是什么？",
    applicable_context: ["定位策略制定", "消费者研究", "市场进入"],
    key_variables: ["洞察的深度", "洞察的真实性", "洞察的可行动性"],
    decision_rules: [
      "洞察必须先于策略——没有洞察就没有方向感",
      "消费者洞察不是数据堆砌，而是找到消费者自己都没说出来的真相",
      "女性都爱美不是洞察——女性怕老怕丑怕被比较才是洞察",
    ],
    anti_patterns: [
      "用数据代替洞察",
      "用常识代替洞察",
      "根本不做洞察就直接做定位",
    ],
    output_implication: "每个候选方向必须有对应的消费者洞察支撑",
  },
  {
    id: "ye-method-repetition",
    theory_source: "ye_maozhong",
    name: "重复是记忆的母亲",
    principle: "一次性的沟通等于没有沟通，持续重复才能进入心智",
    decision_question: "这个定位是否经得起持续重复？",
    applicable_context: ["传播策略", "品牌建设", "定位沉淀"],
    key_variables: ["重复的可持续性", "重复的维度", "消费者的审美疲劳风险"],
    decision_rules: [
      "一次性的大广告不如持续的重复小信息",
      "定位表达要有足够的简洁度来支撑持续重复",
      "一个不能持续重复的定位等于没有定位",
    ],
    anti_patterns: [
      "定位语太复杂无法在广告中持续重复",
      "每个季度的传播主题完全不同",
      "品牌方自己先厌倦了自己的定位而频繁更换",
    ],
    output_implication: "定位语必须简洁到可以持续重复一年以上",
  },
  {
    id: "ye-method-verbal-spread",
    theory_source: "ye_maozhong",
    name: "口语是最高级的传播语言",
    principle: "消费者不会用书面语转述品牌",
    decision_question: "消费者会怎么用他自己的话转述这个定位？",
    applicable_context: ["定位语设计", "品牌口号", "传播内容"],
    key_variables: ["口语化程度", "转述准确度", "转述的主动性"],
    decision_rules: [
      "定位语在文档里再精彩也不如在消费者嘴里说出来精彩",
      "检查标准：去楼下小店店主能不能说给邻居听？",
      "让消费者愿意主动转述的关键：有用、有面子",
    ],
    anti_patterns: [
      "定位语是书面语",
      "定位语太长导致消费者转述时自动省略",
      "定位语太复杂消费者转述时会走样",
    ],
    output_implication: "定位语必须经过口语转述测试",
  },
  {
    id: "ye-method-trigger-word",
    theory_source: "ye_maozhong",
    name: "触发词法则",
    principle: "某些词语天然具有更高的记忆和传播效率",
    decision_question: "这个定位中有没有触发词？",
    applicable_context: ["品牌命名", "定位语撰写", "传播策略"],
    key_variables: ["触发词的记忆度", "触发词的传播力", "触发词的独特性"],
    decision_rules: [
      "某些词天生就比别的词更容易被记住和传播",
      "在定位中嵌入一个触发词可以显著降低传播成本",
      "一个好的触发词本身就值一千万广告费",
    ],
    anti_patterns: [
      "定位语中充斥着消费者每天听到的麻木词语",
      "用了有趣的词但和品牌定位没有关系",
      "触发词太突兀让消费者觉得莫名其妙",
    ],
    output_implication: "定位语中应嵌入至少一个触发词",
  },
  {
    id: "ye-method-selling-point",
    theory_source: "ye_maozhong",
    name: "购买理由比品牌故事更重要",
    principle: "消费者不关心品牌的故事，他们关心为什么要选你",
    decision_question: "这个定位是否给了消费者一个明确的购买理由？",
    applicable_context: ["转化率提升", "销售话术", "定位验证"],
    key_variables: ["购买理由的强度", "购买理由的独特性", "购买理由的真实性"],
    decision_rules: [
      "消费者不关心品牌故事，他们只关心我为什么要选你",
      "好的定位本身就包含一个强有力的购买理由",
      "购买理由必须具体——越抽象越没有说服力",
    ],
    anti_patterns: [
      "用品牌故事替代购买理由",
      "购买理由太抽象",
      "购买理由不具备排他性",
    ],
    output_implication: "每个候选方向必须包含一个清晰的、排他的购买理由",
  },
  {
    id: "ye-ad-no-big-words",
    theory_source: "ye_maozhong",
    name: "不说大话",
    principle: "说人话比说大话难一万倍",
    decision_question: "这个定位是否在说大话？",
    applicable_context: ["定位语撰写", "品牌口号", "传播内容"],
    key_variables: ["语言的具体度", "语言的真诚度", "语言的差异化"],
    decision_rules: [
      "广告中最浪费钱的就是消费者看不懂的大话",
      "引领生活方、重新定义XX、赋能——这些词消费者根本听不懂",
      "越是大品牌越说小话",
    ],
    anti_patterns: [
      "用宏大词汇包装普通的商业逻辑",
      "定位语在行业大会上很有面子但消费者听不懂",
      "竞品都在说大话时以为自己也应该说大话",
    ],
    output_implication: "定位语中不应出现任何消费者听不懂的抽象词汇",
  },
  {
    id: "ye-plan-execution-first",
    theory_source: "ye_maozhong",
    name: "执行比策略重要",
    principle: "中国市场上90%的营销失败不是策略错了，是执行不到位",
    decision_question: "这个定位在中国市场的执行落地有把握吗？",
    applicable_context: ["执行评估", "资源匹配", "落地可行性"],
    key_variables: ["执行能力", "可交付程度", "资源匹配度"],
    decision_rules: [
      "好的策略遇到差的执行等于零效果",
      "一个可执行的一般策略远胜于一个不可执行的完美策略",
      "在执行力有限的情况下，宁可选简单但能执行到位的定位",
    ],
    anti_patterns: [
      "策略很精彩但团队做不出来",
      "低估了中国市场执行的复杂性",
      "认为创意好就够了",
    ],
    output_implication: "不可执行的定位在叶茂中视角下直接降级",
  },
  {
    id: "ye-plan-local-reality",
    theory_source: "ye_maozhong",
    name: "中国市场的特殊性",
    principle: "中国市场与国际市场有本质差异",
    decision_question: "这个定位是否考虑了中国市场现实？",
    applicable_context: ["中国品牌定位", "下沉市场", "区域品牌"],
    key_variables: ["中国市场特征", "消费者行为差异", "基础设施与渠道差异"],
    decision_rules: [
      "中国消费者更感性、更冲动、品牌忠诚度更低",
      "中国市场的渠道比品牌更有话语权",
      "中国消费者对价格更敏感",
    ],
    anti_patterns: [
      "照搬西方品牌定位理论忽略中国市场特征",
      "认为中国消费者和西方消费者一样理性",
      "忽略了中国各区域的市场差异",
    ],
    output_implication: "定位策略必须适配中国市场的具体条件",
  },
  {
    id: "ye-campaign-small-test",
    theory_source: "ye_maozhong",
    name: "小范围试错",
    principle: "不要一上来就大张旗鼓——先用最小成本验证定位的有效性",
    decision_question: "这个定位能否用最小的成本先验证？",
    applicable_context: ["新品牌", "预算有限", "不确定的定位"],
    key_variables: ["验证成本", "验证周期", "验证指标"],
    decision_rules: [
      "大干快上是最大的浪费——在验证之前就投入大预算",
      "先用一家店、一个社区、一个渠道验证定位效果",
      "验证至少需要30天——首周的新鲜感不能代表长期有效",
    ],
    anti_patterns: [
      "一上来就大规模铺开",
      "验证时间太短",
      "验证指标太多太复杂",
    ],
    output_implication: "所有定位都应设计30天最小验证方案",
  },
  {
    id: "ye-campaign-opportunity",
    theory_source: "ye_maozhong",
    name: "借势比造势更重要",
    principle: "借消费者的既有认知之势，比凭空创造认知容易一万倍",
    decision_question: "这个定位借了消费者的什么既有认知之势？",
    applicable_context: ["品牌定位", "传播策略", "市场教育"],
    key_variables: ["可借之势的类型", "之势的强度", "之势的匹配度"],
    decision_rules: [
      "借势比造势更重要——消费者已经接受的概念不需要你重新教育",
      "可借之势：已有的品类认知、文化共识、社会热点",
      "最好的定位是让消费者觉得本来就应该这样",
    ],
    anti_patterns: [
      "逆着消费者的既有认知做定位",
      "明明有势可借却偏要造势",
      "借势但借错了势",
    ],
    output_implication: "候选方向应优先利用消费者已有的认知趋势",
  },
];
